# =================== AIPass ====================
# Name: seed_ops.py
# Description: Passport seeds — tracked identity, untracked live file (TDPLAN-0017)
# Version: 1.0.0
# Created: 2026-08-28
# Modified: 2026-08-28
# =============================================

"""Passport seeds: the identity that ships with the repo (TDPLAN-0017).

A live passport is ``.trinity/passport.json`` and it is GITIGNORED, on purpose:
tracking it is pull-hostile (refusals, conflicts, ``reset --hard`` destroying an
agent's identity). The cost of that correctness is that five months of evolved
identity never reaches a clone — a fresh install mints every citizen from the one
generic template and the souls stay on the machine that grew them.

The seed closes that gap without touching the ignore. Each branch carries a
TRACKED ``.aipass/passport.seed.json`` — its live passport minus the facts that
are true only of one machine::

    citizenship.registered     the live file asserts it; a seed is not a citizen
    citizenship.registry_id    this machine's project credential
    citizenship.citizen_id     this machine's per-citizen UUID
    citizenship.seed           the stamp itself (see below)

Everything else is carried VERBATIM — residency, dates, path, the whole identity
block. The seed is not an example file and never a hand-edited one: it is
GENERATED by ``drone @spawn export-seeds`` from the live passport, which is what
keeps it from rotting the way a checked-in ``.env.example`` does.

The stamp is the one field that goes the other way. A passport minted FROM a seed
records which seed it came from::

    "citizenship": {..., "seed": {"version": "2.0.0", "sha256": "<file bytes>"}}

That is dpkg's md5sums pattern, and it is the whole reason update/merge machinery
could be deferred: with the stamp, a future "the shipped seed changed" question is
a three-way decision (shipped-then, shipped-now, live-now) instead of a guess.
A template mint gets NO stamp — it came from no seed, and an empty stamp would be
a claim about provenance that is not true.

**Schema knowledge is borrowed, never re-declared.** ``BLOCK_ORDER``, ``KEY_ORDER``
and ``SCHEMA_VERSION`` come from ``passport_migration`` — the module that already
owns the 2.0 shape. This module adds exactly one key to that knowledge
(``citizenship.seed``, optional) and appends it at the END of the citizenship
block, which is precisely where ``passport_migration._order_block`` puts a key it
does not recognise. A stamped passport therefore reorders to itself if the
migration is ever re-run over it.

**Refusal is the safe direction, in both lanes.** ``export_seeds`` refuses to
write a seed for a passport that does not validate (a bad seed shipped to every
clone is worse than a missing one), and ``mint_from_seed`` refuses to return a
passport that does not validate, so an invalid seed can never reach disk as
somebody's identity.
"""

import copy
import hashlib
import json
from pathlib import Path

from aipass.prax.apps.modules.logger import system_logger as logger

from aipass.spawn.apps.handlers.atomic_write import atomic_write_text
from aipass.spawn.apps.handlers.class_registry import resolve_template_class
from aipass.spawn.apps.handlers.json import json_handler
from aipass.spawn.apps.handlers.passport_migration import (
    BLOCK_ORDER,
    EXPECTED_FLEET,
    KEY_ORDER,
    SCHEMA_VERSION,
    discover_passports,
    repo_root,
)

__all__ = [
    "MACHINE_LOCAL_CITIZENSHIP",
    "OPTIONAL_KEYS",
    "SEED_DIR_NAME",
    "SEED_FILE_NAME",
    "SEED_RELATIVE_PATH",
    "STAMP_KEY",
    "SeedError",
    "build_seed",
    "canonical_text",
    "export_seed",
    "export_seeds",
    "find_seed",
    "load_seed",
    "mint_and_write",
    "mint_from_seed",
    "seed_fingerprint",
    "seed_path_for",
    "seed_stamp",
    "validate_passport",
    "validate_seed",
]


# =============================================================================
# CONTRACT
# =============================================================================

SEED_DIR_NAME = ".aipass"
SEED_FILE_NAME = "passport.seed.json"
SEED_RELATIVE_PATH = f"{SEED_DIR_NAME}/{SEED_FILE_NAME}"

# The optional canonical field a seed-minted passport carries. schema_version
# stays 2.0.0 — this is an additive optional machine-local field, not a bump.
STAMP_KEY = "seed"
STAMP_FIELDS = ("version", "sha256")

# Facts that are true of ONE MACHINE and must never ship in a tracked seed.
# This tuple is the privacy leak-guard's definition as well as the strip list.
MACHINE_LOCAL_CITIZENSHIP = ("registered", "registry_id", "citizen_id", STAMP_KEY)

# Keys the 2.0 shape allows but does not require. class_extension exists on
# devpulse alone (DPLAN-0288 prose); the stamp exists only on a seed mint.
OPTIONAL_KEYS = {
    "citizenship": (STAMP_KEY,),
    "identity": ("class_extension",),
}

# Seeds are only defined for CORE citizens — the seed path in the ruling is
# ``src/aipass/<branch>/.aipass/passport.seed.json``. Residents live in
# ``projects/<project>/`` and belong to their own project's repo.
SEED_RESIDENCY = "core"

# Shape rules, kept deliberately small: enough that "invalid seed refuses" has
# teeth, not a second schema engine. Everything not listed must be a string —
# which is why ``traits`` is here: the 1.x fleet carried it as prose, and a
# string sneaking back in is the exact regression this table catches.
_FIELD_TYPES = {
    ("document_metadata", "tags"): (list, "a list"),
    ("identity", "what_i_do"): (list, "a list"),
    ("identity", "what_i_dont_do"): (list, "a list"),
    ("identity", "traits"): (list, "a list"),
    ("identity", "principles"): (list, "a list"),
    ("citizenship", "registered"): (bool, "true/false"),
    ("citizenship", "communications"): (bool, "true/false"),
    ("citizenship", "memory"): (bool, "true/false"),
}
_DEFAULT_FIELD_TYPE = (str, "a string")

# The stamp is the one field with a shape of its own — see _validate_stamp.
_STAMP_FIELD = {("citizenship", STAMP_KEY)}
_REQUIRED_NON_EMPTY = {
    ("document_metadata", "document_name"),
    ("document_metadata", "schema_version"),
    ("branch_info", "branch_name"),
    ("branch_info", "path"),
    ("citizenship", "residency"),
    ("identity", "citizen_class"),
}


class SeedError(Exception):
    """A seed that cannot be trusted. Callers refuse rather than write."""


def _key_order(section: str) -> tuple:
    """Canonical key order for a block, with the stamp appended to citizenship.

    The stamp's position is not a free choice: appending it is exactly what
    ``passport_migration._order_block`` does with a key it does not recognise,
    so a stamped passport is already in the order that module would emit.
    """
    if section == "citizenship":
        return KEY_ORDER["citizenship"] + (STAMP_KEY,)
    return KEY_ORDER[section]


# =============================================================================
# PATHS
# =============================================================================


def seed_path_for(branch_dir) -> Path:
    """Return the seed path for a branch directory — ``<branch>/.aipass/...``.

    The seed lives INSIDE the branch it describes. That is what makes a
    name collision impossible: there is no lookup by branch name that could
    hand one citizen another citizen's identity.
    """
    return Path(branch_dir) / SEED_DIR_NAME / SEED_FILE_NAME


def find_seed(branch_dir) -> Path | None:
    """Return the branch's seed file, or None when it carries none."""
    candidate = seed_path_for(branch_dir)
    return candidate if candidate.is_file() else None


# =============================================================================
# VALIDATION — one schema, two lanes (a seed is a passport minus machine-local)
# =============================================================================


def _validate_block(block: dict, section: str, *, kind: str) -> list[str]:
    """Return every problem with one block. Empty list means valid."""
    problems: list[str] = []
    order = _key_order(section)
    optional = set(OPTIONAL_KEYS.get(section, ()))

    forbidden = set(MACHINE_LOCAL_CITIZENSHIP) if (kind == "seed" and section == "citizenship") else set()
    required = [key for key in order if key not in optional and key not in forbidden]

    for key in forbidden & set(block):
        problems.append(
            f"{section}.{key} is machine-local and must never appear in a seed (it is minted fresh per install)"
        )
    for key in required:
        if key not in block:
            problems.append(f"{section}.{key} is missing")
    for key in block:
        if key not in order:
            problems.append(f"{section}.{key} is not a field of the {SCHEMA_VERSION} schema")

    present = [key for key in block if key in order]
    if present != [key for key in order if key in block]:
        problems.append(f"{section} keys are out of canonical order: {' > '.join(present)}")

    problems.extend(_validate_types(block, section))
    return problems


def _validate_types(block: dict, section: str) -> list[str]:
    """Type and emptiness rules for the fields whose shape is load-bearing."""
    problems: list[str] = []
    for key, value in block.items():
        field = (section, key)
        if field in _STAMP_FIELD:
            problems.extend(_validate_stamp(value))
        else:
            expected, label = _FIELD_TYPES.get(field, _DEFAULT_FIELD_TYPE)
            if not isinstance(value, expected):
                problems.append(f"{section}.{key} must be {label}, found {type(value).__name__}")

        if field in _REQUIRED_NON_EMPTY and isinstance(value, str) and not value.strip():
            problems.append(f"{section}.{key} is empty")
    return problems


def _validate_stamp(stamp) -> list[str]:
    """The stamp is a closed two-field record — a half-stamp is worse than none."""
    if not isinstance(stamp, dict):
        return [f"citizenship.{STAMP_KEY} must be an object, found {type(stamp).__name__}"]
    problems = [f"citizenship.{STAMP_KEY}.{key} is missing" for key in STAMP_FIELDS if key not in stamp]
    problems += [f"citizenship.{STAMP_KEY}.{key} is not a stamp field" for key in stamp if key not in STAMP_FIELDS]
    problems += [
        f"citizenship.{STAMP_KEY}.{key} must be a string"
        for key in STAMP_FIELDS
        if key in stamp and not isinstance(stamp[key], str)
    ]
    return problems


def _validate_document(document, *, kind: str) -> list[str]:
    """Return every problem with a passport-shaped document. Empty means valid.

    Args:
        document: Parsed JSON document.
        kind: "passport" (machine-local facts REQUIRED) or "seed" (FORBIDDEN).

    Returns:
        Human-readable problems, in document order. Never raises.
    """
    if not isinstance(document, dict):
        return [f"document root is not a JSON object (found {type(document).__name__})"]

    problems: list[str] = []
    for section in BLOCK_ORDER:
        if section not in document:
            problems.append(f"{section} block is missing")
    for key in document:
        if key not in BLOCK_ORDER:
            problems.append(f"top-level '{key}' is not a block of the {SCHEMA_VERSION} schema")

    present = [key for key in document if key in BLOCK_ORDER]
    if present != [key for key in BLOCK_ORDER if key in document]:
        problems.append(f"blocks are out of canonical order: {' > '.join(present)}")

    for section in BLOCK_ORDER:
        block = document.get(section)
        if block is None:
            continue
        if not isinstance(block, dict):
            problems.append(f"{section} is not a JSON object (found {type(block).__name__})")
            continue
        problems.extend(_validate_block(block, section, kind=kind))

    declared = (document.get("document_metadata") or {}).get("schema_version")
    if isinstance(declared, str) and declared and declared != SCHEMA_VERSION:
        problems.append(f"document_metadata.schema_version is {declared!r}, expected {SCHEMA_VERSION!r}")

    identity = document.get("identity")
    if isinstance(identity, dict) and "citizen_class" in identity:
        # The class registry is the authority on what a passport may claim —
        # "admin" and the retired names refuse here rather than being minted.
        try:
            resolve_template_class(identity)
        except ValueError as exc:
            # Collected, not raised: this function reports EVERY problem so one
            # bad field cannot hide the next. It goes on the record too — a
            # refused class is a fact about a real identity, not a test detail.
            logger.warning("[seeds] citizen_class refused: %s", exc)
            problems.append(f"identity.citizen_class: {exc}")

    return problems


def validate_seed(document) -> list[str]:
    """Problems with a seed document — machine-local fields are FORBIDDEN."""
    return _validate_document(document, kind="seed")


def validate_passport(document) -> list[str]:
    """Problems with a live passport document — machine-local fields REQUIRED."""
    return _validate_document(document, kind="passport")


# =============================================================================
# TRANSFORM — pure, no filesystem
# =============================================================================


def _ordered_block(block: dict, section: str, drop: tuple = ()) -> dict:
    """Emit a block in canonical key order, dropping ``drop``.

    Unrecognised keys are APPENDED, never removed — the same preserve-and-report
    rule ``passport_migration`` follows. Validation is what refuses them; a
    transform that silently deleted a field nobody knew about would be the worse
    failure, because the seed is the thing that ships.
    """
    order = _key_order(section)
    ordered = {key: block[key] for key in order if key in block and key not in drop}
    for key, value in block.items():
        if key in order or key in drop:
            continue
        ordered[key] = value
    return ordered


def build_seed(passport: dict) -> dict:
    """Transform a live passport into its seed. Pure — no filesystem.

    Strips exactly the four machine-local citizenship facts and re-emits every
    block in canonical key order. Nothing else is touched: residency, dates,
    path, and the whole identity block carry across verbatim.

    Args:
        passport: A parsed live passport document.

    Returns:
        The seed document, ready to serialise.

    Raises:
        SeedError: The passport root is not a JSON object.
    """
    if not isinstance(passport, dict):
        raise SeedError(f"passport root is not a JSON object (found {type(passport).__name__})")

    seed: dict = {}
    for section in BLOCK_ORDER:
        if section not in passport:
            continue
        block = passport[section]
        if not isinstance(block, dict):
            seed[section] = block
            continue
        drop = MACHINE_LOCAL_CITIZENSHIP if section == "citizenship" else ()
        seed[section] = _ordered_block(block, section, drop=drop)

    for key, value in passport.items():
        if key not in BLOCK_ORDER:
            seed[key] = value
    return seed


def canonical_text(document: dict) -> str:
    """Serialise a seed or passport the one way either is ever written.

    Order-sensitive and ``ensure_ascii=False`` — the same form
    ``passport_migration`` writes, so a seed, a migrated passport and a
    seed-minted passport are byte-comparable instead of only value-equal.
    """
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def seed_fingerprint(path) -> str:
    """SHA-256 of the seed FILE's bytes, hex.

    Deliberately the bytes on disk rather than a re-serialised document: the
    stamp must answer "which file was I minted from", and a hash of a
    normalised in-memory copy could match a file that differs.
    """
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def seed_stamp(seed: dict, path) -> dict:
    """Build the ``citizenship.seed`` stamp for a mint from ``path``."""
    version = (seed.get("document_metadata") or {}).get("version", "")
    return {"version": version, "sha256": seed_fingerprint(path)}


def load_seed(path) -> dict:
    """Read and validate a seed file.

    Args:
        path: Path to a ``passport.seed.json``.

    Returns:
        The validated seed document.

    Raises:
        SeedError: Unreadable, unparseable, or not a valid 2.0 seed. The reason
            names every problem — a caller that refuses must be able to say why.
    """
    path = Path(path)
    try:
        raw = path.read_bytes().decode("utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise SeedError(f"seed at {path} could not be read: {exc}") from exc

    try:
        document = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise SeedError(f"seed at {path} is not valid JSON: {exc}") from exc

    problems = validate_seed(document)
    if problems:
        raise SeedError(
            f"seed at {path} is not a valid {SCHEMA_VERSION} passport seed:\n  - " + "\n  - ".join(problems)
        )
    return document


def mint_from_seed(seed: dict, seed_file, *, branch_name: str, registry_id: str, citizen_id: str) -> dict:
    """Render a live passport from a seed. Pure apart from hashing the seed file.

    The three machine-local facts are minted FRESH exactly as a template mint
    mints them — a seed carries an identity, never an installation.

    Args:
        seed: A validated seed document.
        seed_file: The file the seed was read from — hashed into the stamp.
        branch_name: The branch being minted. Must match the seed's own
            ``branch_info.branch_name``.
        registry_id: The project credential (registry ``metadata.id``).
        citizen_id: The freshly minted per-citizen UUID.

    Returns:
        A valid 2.0 passport document carrying ``citizenship.seed``.

    Raises:
        SeedError: The seed belongs to another branch, or the rendered passport
            does not validate. Nothing is written either way.
    """
    declared = (seed.get("branch_info") or {}).get("branch_name", "")
    if declared != branch_name:
        raise SeedError(
            f"seed at {seed_file} belongs to branch {declared!r}, not {branch_name!r} — "
            f"spawn will not mint one citizen's identity into another."
        )

    passport = copy.deepcopy(seed)
    citizenship = dict(passport.get("citizenship") or {})
    citizenship["registered"] = True
    citizenship["registry_id"] = registry_id
    citizenship["citizen_id"] = citizen_id
    citizenship[STAMP_KEY] = seed_stamp(seed, seed_file)
    passport["citizenship"] = _ordered_block(citizenship, "citizenship")

    problems = validate_passport(passport)
    if problems:
        raise SeedError(
            f"passport rendered from {seed_file} is not a valid {SCHEMA_VERSION} passport, "
            f"nothing written:\n  - " + "\n  - ".join(problems)
        )
    return passport


def mint_and_write(seed_file, passport_path, *, branch_name: str, registry_id: str, citizen_id: str) -> dict:
    """Load a seed, mint the live passport, and write it atomically.

    The whole render is validated before anything touches disk (``load_seed``
    and ``mint_from_seed`` both refuse), and the write is atomic + canonical —
    the same serialisation seeds themselves use (never the shared JSON writer,
    which escapes the non-ASCII passport prose is full of), so seed and minted
    passport stay byte-comparable rather than only value-equal.

    Args:
        seed_file: Path to the branch's tracked seed.
        passport_path: Destination ``.trinity/passport.json``.
        branch_name: The branch being minted.
        registry_id: The project credential (registry ``metadata.id``).
        citizen_id: The freshly minted per-citizen UUID.

    Returns:
        The rendered passport document (already on disk when this returns).

    Raises:
        SeedError: The seed or the rendered passport failed validation —
            nothing was written.
        OSError: The passport could not be written.
    """
    seed = load_seed(seed_file)
    passport = mint_from_seed(
        seed,
        seed_file,
        branch_name=branch_name,
        registry_id=registry_id,
        citizen_id=citizen_id,
    )
    passport_path = Path(passport_path)
    passport_path.parent.mkdir(parents=True, exist_ok=True)
    atomic_write_text(passport_path, canonical_text(passport))
    return passport


# =============================================================================
# EXPORT — live passport -> tracked seed, dry run by default
# =============================================================================


def export_seed(target, *, confirm: bool = False) -> dict:
    """Export one branch's seed. Writes nothing unless ``confirm``.

    Args:
        target: A ``PassportTarget`` from ``discover_passports``.
        confirm: False (default) plans only — no write, no mtime change.

    Returns:
        A per-branch record: branch, paths, action, changed, written, error.
    """
    seed_file = seed_path_for(target.branch_dir)
    record: dict = {
        "branch": target.branch_dir.name.lower(),
        "passport": str(target.path),
        "seed": str(seed_file),
        "residency": target.residency,
        "action": "skipped",
        "changed": False,
        "written": False,
        "error": None,
    }

    try:
        document = json.loads(target.path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        record["error"] = f"unreadable passport: {exc}"
        logger.error("[export-seeds] %s: %s", target.path, exc)
        return record

    problems = validate_passport(document)
    if problems:
        # A bad seed shipped to every clone is worse than a missing one, so a
        # passport that does not validate does not get a seed — it gets named.
        record["error"] = f"live passport is not a valid {SCHEMA_VERSION} passport: " + "; ".join(problems)
        logger.error("[export-seeds] %s skipped: %s", record["branch"], record["error"])
        return record

    try:
        seed = build_seed(document)
    except SeedError as exc:
        record["error"] = str(exc)
        logger.error("[export-seeds] %s skipped: %s", record["branch"], exc)
        return record

    seed_problems = validate_seed(seed)
    if seed_problems:
        record["error"] = "built seed did not validate: " + "; ".join(seed_problems)
        logger.error("[export-seeds] %s skipped: %s", record["branch"], record["error"])
        return record

    wanted = canonical_text(seed)
    current = None
    if seed_file.exists():
        try:
            current = seed_file.read_text(encoding="utf-8")
        except OSError as exc:
            # Refuse rather than overwrite: a seed we cannot read is a seed we
            # cannot compare, and a blind write would lose whatever it holds.
            record["error"] = f"existing seed unreadable: {exc}"
            logger.error("[export-seeds] %s skipped: %s", record["branch"], exc)
            return record

    if current == wanted:
        # Idempotency is the measurement, not a claim: a second run reports
        # every seed "current" and touches nothing at all.
        record["action"] = "current"
        return record

    record["action"] = "updated" if current is not None else "created"
    record["changed"] = True
    if not confirm:
        return record

    try:
        seed_file.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_text(seed_file, wanted)
    except OSError as exc:
        record["error"] = f"write failed: {exc}"
        record["changed"] = False
        record["action"] = "skipped"
        logger.error("[export-seeds] %s write failed: %s", record["branch"], exc)
        return record

    record["written"] = True
    logger.info("[export-seeds] %s seed %s (%s)", record["branch"], record["action"], seed_file)
    return record


def export_seeds(root=None, *, only: str | None = None, confirm: bool = False) -> dict:
    """Export every core citizen's seed and return a measured receipt.

    Discovery reuses ``passport_migration.discover_passports`` — the same glob
    that found the fleet for the 2.0 migration, so the two fleet-wide commands
    can never disagree about who the fleet is. Residents are counted and
    reported but NOT exported: the seed path in the ruling is
    ``src/aipass/<branch>/.aipass/passport.seed.json``, and a resident's identity
    belongs to its own project's repo, not to AIPass's.

    Args:
        root: Repo root to scan. Defaults to the live repo root.
        only: Restrict to one branch (``@`` and case are ignored).
        confirm: False (default) is a dry run — nothing is written at all.

    Returns:
        Receipt dict: root, confirm, counts, per-branch records, errors, and a
        ``baseline`` block comparing the discovered core set to the measured fleet.
    """
    base = Path(root) if root is not None else repo_root()

    discovered = discover_passports(base)
    core = [t for t in discovered if t.residency == SEED_RESIDENCY]
    skipped_resident = len(discovered) - len(core)

    wanted = (only or "").lstrip("@").strip().lower()
    targets = [t for t in core if t.branch_dir.name.lower() == wanted] if wanted else core

    records = [export_seed(target, confirm=confirm) for target in targets]
    errors = [{"branch": r["branch"], "error": r["error"]} for r in records if r["error"]]

    # An ALARM, never a gate — the discovered set is the truth, this says when
    # it stopped matching what was measured at build time.
    baseline = {
        "expected_core": EXPECTED_FLEET["core"],
        "discovered_core": len(core),
        "filtered": bool(wanted),
        "matches": len(core) == EXPECTED_FLEET["core"],
    }

    receipt = {
        "root": str(base),
        "confirm": confirm,
        "only": wanted or None,
        "scanned": len(records),
        "created": sum(1 for r in records if r["action"] == "created"),
        "updated": sum(1 for r in records if r["action"] == "updated"),
        "current": sum(1 for r in records if r["action"] == "current"),
        "changed": sum(1 for r in records if r["changed"]),
        "written": sum(1 for r in records if r["written"]),
        "skipped_resident": skipped_resident,
        "errors": errors,
        "seeds": records,
        "baseline": baseline,
    }

    # The WRITE is the event worth a durable record — a dry run leaves the
    # filesystem untouched and is logged by the CLI layer instead.
    if confirm and receipt["written"]:
        json_handler.log_operation(
            "passport_seeds_exported",
            data={"written": receipt["written"], "scanned": receipt["scanned"], "root": receipt["root"]},
        )

    return receipt
