# =================== AIPass ====================
# Name: operations.py
# Description: Logging Operations
# Version: 1.1.0
# Created: 2025-11-10
# Modified: 2026-08-04
# =============================================

"""
PRAX Logging Operations

Operation logging and configuration management for prax logger.
"""

import json
from datetime import datetime, timezone
from typing import Dict, Optional

# Import from prax config
from aipass.prax.apps.handlers.config.load import (
    DEFAULT_LOCAL_LOGS,
    DEFAULT_SYSTEM_LOGS,
    PRAX_JSON_DIR,
)
from aipass.prax.apps.handlers.logging.direct import get_direct_logger
from aipass.prax.apps.handlers.json import json_handler

logger = get_direct_logger()

# Module constants
MODULE_NAME = "prax_logger"
CONFIG_FILE = PRAX_JSON_DIR / f"{MODULE_NAME}_config.json"
DATA_FILE = PRAX_JSON_DIR / f"{MODULE_NAME}_data.json"
LOG_FILE = PRAX_JSON_DIR / f"{MODULE_NAME}_log.json"


def log_operation(message: str, data: Optional[Dict] = None):
    """Log prax_logging operations to JSON log file

    Args:
        message: Operation description
        data: Optional operation data dict
    """
    entry = {"timestamp": datetime.now(timezone.utc).isoformat(), "operation": message, "data": data or {}}

    # Load existing log
    log_entries = []
    if LOG_FILE.exists():
        try:
            with open(LOG_FILE, "r", encoding="utf-8") as f:
                log_entries = json.load(f)
        except Exception as e:
            logger.warning("Failed to load log file %s, resetting entries: %s", LOG_FILE, e)
            log_entries = []

    # Add new entry
    log_entries.append(entry)

    # Keep only last 1000 entries
    if len(log_entries) > 1000:
        log_entries = log_entries[-1000:]

    # Save log
    with open(LOG_FILE, "w", encoding="utf-8") as f:
        json.dump(log_entries, f, indent=2, ensure_ascii=False)
    json_handler.log_operation("log_operation_performed", {"message": message})


def create_config_file():
    """Create default config file if it doesn't exist"""
    if not CONFIG_FILE.exists():
        # Every key here must be one a reader actually looks for. The previous
        # template emitted log_level/max_log_size_mb/backup_count/console_output/
        # file_output/rotation_enabled/debug_prints/log_directories at this level,
        # where nothing reads them: load_log_config() wants config.system_logs and
        # config.local_logs, and get_debug_prints_enabled() wants
        # debug_prints_enabled, not debug_prints. Every install generated by the
        # old template therefore advertised 5 backups of 10 MB while the code ran
        # 1 backup of 200,000 bytes — a 250x gap that read as configuration, and
        # invisible in review because prax_json/ is gitignored. Sections come
        # from load.py's constants rather than literals so the file can never
        # drift from the defaults it is meant to mirror.
        default_config = {
            "module_name": MODULE_NAME,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "config": {
                "system_logs": dict(DEFAULT_SYSTEM_LOGS),
                "local_logs": dict(DEFAULT_LOCAL_LOGS),
                "log_format": "%(asctime)s | %(name)s | %(levelname)s | %(message)s",
                "date_format": "%Y-%m-%d %H:%M:%S",
                "debug_prints_enabled": False,
            },
        }
        try:
            with open(CONFIG_FILE, "w", encoding="utf-8") as f:
                json.dump(default_config, f, indent=2, ensure_ascii=False)
            logger.info("Config file created: %s", CONFIG_FILE)
        except Exception as e:
            logger.warning("Failed to create config file: %s", e)
