# =================== AIPass ====================
# Name: test_slash_relay.py
# Description: Tests for relaying CC informational slash-command stdout to Telegram
# Version: 1.0.0
# Created: 2026-08-02
# Modified: 2026-08-02
# =============================================

"""
Tests for the informational slash-command relay (/context).

A CC local command produces NO assistant turn — the Stop hook never fires — so
this path deliberately writes no pending file and owns its own completion.
That is the property most of these tests defend, alongside the parse seam and
the scope guard.

Tests cover:
  - Parsing a local-command-stdout entry from both transcript shapes
  - The ANSI-panel variant and its clean-markdown isMeta twin
  - Baseline bounding + twin lookahead (scope guard: no surprise echo)
  - Telegram formatting: ANSI stripped, HTML escaped, <pre> wrapped, chunked
  - The allowlist: /context in, /cost out, config override honoured
  - No-wedge completion: no pending file, relay on success, honest text on timeout

All network (urllib) and process (tmux) calls are mocked. No real Telegram API,
no real tmux, no real Claude session.
"""

import json
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from aipass.skills.lib.telegram.apps.handlers.base_bot import (
    ANSI_ESCAPE_RE,
    DEFAULT_INFORMATIONAL_COMMANDS,
    SLASH_STDOUT_TIMEOUT_SECONDS,
    BaseBot,
)


# =============================================
# REAL /context PAYLOAD (verbatim excerpt)
# =============================================

# Copied verbatim from a real transcript entry written by CC (type=system,
# subtype=local_command). Truncated in the middle of the MCP table only — the
# wrapper, header, blank lines, two-space markdown line breaks, pipe tables and
# trailing newline are exactly as CC emitted them.
REAL_CONTEXT_STDOUT = """<local-command-stdout>## Context Usage

**Model:** claude-fable-5
**Tokens:** 174.1k / 350k (50%)

### Estimated usage by category

| Category | Tokens | Percentage |
|----------|--------|------------|
| System prompt | 5.6k | 1.6% |
| System tools | 22.1k | 6.3% |
| MCP tools (deferred) | 36.3k | 10.4% |
| Memory files | 2k | 0.6% |
| Messages | 142.9k | 40.8% |
| Free space | 142.4k | 40.7% |
| Autocompact buffer | 33k | 9.4% |

### MCP Tools

| Tool | Server | Tokens |
|------|--------|--------|
| mcp__claude_ai_Gmail__create_draft | claude_ai_Gmail | 1.5k |
| mcp__claude_ai_Gmail__get_message | claude_ai_Gmail | 827 |

</local-command-stdout>"""

# The same command in the other shape CC produces: a rendered TUI panel with
# colour escapes and box-drawing characters.
REAL_ANSI_STDOUT = (
    "<local-command-stdout> \x1b[1mContext Usage\x1b[22m\n"
    "\x1b[38;5;244m⛁ \x1b[38;5;246m⛁ ⛁ ⛁ \x1b[38;5;174m⛀ "
    "\x1b[38;5;220m⛀ \x1b[38;5;140m⛁ ⛁\x1b[39m\n"
    "\x1b[1mTokens:\x1b[22m 57.8k / 1m (6%)\n"
    "</local-command-stdout>"
)

# The isMeta twin CC writes immediately behind the ANSI panel.
REAL_TWIN_MARKDOWN = "## Context Usage\n\n**Model:** claude-opus-4-8  \n**Tokens:** 57.8k / 1m (6%)\n"


# =============================================
# TRANSCRIPT ENTRY BUILDERS
# =============================================


def stdout_entry(payload: str, at_message: bool = False) -> dict:
    """A type=system, subtype=local_command entry carrying command stdout."""
    entry: dict = {"type": "system", "subtype": "local_command", "level": "info", "isMeta": False}
    if at_message:
        entry["message"] = {"role": "user", "content": payload}
    else:
        entry["content"] = payload
    return entry


def twin_entry(markdown: str) -> dict:
    """The isMeta user entry carrying the clean-markdown twin of a TUI panel."""
    return {"type": "user", "isMeta": True, "message": {"role": "user", "content": markdown}}


def command_name_entry() -> dict:
    """CC's preamble entry — same type/subtype as stdout, but no payload."""
    return stdout_entry("<command-name>/context</command-name>\n<command-args></command-args>")


def caveat_entry() -> dict:
    """The isMeta caveat wrapper that precedes a local command. Never the payload."""
    return twin_entry(
        "<local-command-caveat>Caveat: The messages below were generated by the user.</local-command-caveat>"
    )


def write_transcript(path: Path, entries: list[dict]) -> None:
    path.write_text("\n".join(json.dumps(e) for e in entries) + "\n", encoding="utf-8")


# =============================================
# FIXTURES
# =============================================


@pytest.fixture
def bot(tmp_path):
    """A BaseBot with pending/network/tmux seams neutralised."""
    workdir = tmp_path / "workdir"
    workdir.mkdir()
    with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.PENDING_DIR", tmp_path):
        instance = BaseBot(
            bot_id="relay_bot",
            bot_token="123:FAKETOKEN",
            work_dir=workdir,
            bot_name="Relay Bot",
            allowed_user_ids=[111],
        )
        instance.pending_file = tmp_path / "bot-relay_bot.json"
    instance.send_message = MagicMock(return_value={"message_id": 42})
    instance.edit_message = MagicMock(return_value=True)
    instance.inject_message = MagicMock(return_value=True)
    instance.ensure_tmux_session = MagicMock(return_value=True)
    return instance


# =============================================
# 1. PARSING THE STDOUT ENTRY
# =============================================


class TestExtractLocalCommandStdout:
    """The parse seam against real CC output."""

    def test_extracts_real_context_payload_from_top_level_content(self, bot):
        result = bot._extract_local_command_stdout(stdout_entry(REAL_CONTEXT_STDOUT))
        assert result is not None
        assert result.startswith("## Context Usage")
        assert "| System prompt | 5.6k | 1.6% |" in result

    def test_strips_the_wrapper_tags(self, bot):
        result = bot._extract_local_command_stdout(stdout_entry(REAL_CONTEXT_STDOUT))
        assert "<local-command-stdout>" not in result
        assert "</local-command-stdout>" not in result

    def test_reads_the_older_message_content_location(self, bot):
        result = bot._extract_local_command_stdout(stdout_entry(REAL_CONTEXT_STDOUT, at_message=True))
        assert result is not None
        assert result.startswith("## Context Usage")

    def test_command_name_preamble_is_not_stdout(self, bot):
        assert bot._extract_local_command_stdout(command_name_entry()) is None

    def test_unrelated_entry_returns_none(self, bot):
        assert bot._extract_local_command_stdout({"type": "assistant", "message": {"content": "hi"}}) is None

    def test_missing_close_tag_still_yields_payload(self, bot):
        """A half-written entry should degrade to its content, not to nothing."""
        partial = "<local-command-stdout>## Context Usage\n\n**Tokens:** 1k"
        assert bot._extract_local_command_stdout(stdout_entry(partial)) == "## Context Usage\n\n**Tokens:** 1k"


class TestExtractMetaCommandText:
    """The clean-markdown twin of a rendered TUI panel."""

    def test_extracts_twin_markdown(self, bot):
        assert bot._extract_meta_command_text(twin_entry(REAL_TWIN_MARKDOWN)) == REAL_TWIN_MARKDOWN.strip()

    def test_caveat_wrapper_is_never_the_payload(self, bot):
        assert bot._extract_meta_command_text(caveat_entry()) is None

    def test_non_meta_entry_ignored(self, bot):
        entry = twin_entry(REAL_TWIN_MARKDOWN)
        entry["isMeta"] = False
        assert bot._extract_meta_command_text(entry) is None

    def test_empty_content_ignored(self, bot):
        assert bot._extract_meta_command_text(twin_entry("   ")) is None


# =============================================
# 2. SCANNING THE TRANSCRIPT
# =============================================


class TestScanTranscript:
    """Baseline bounding, variant preference, and the lookahead bound."""

    def test_finds_markdown_variant_and_reports_it_clean(self, bot, tmp_path):
        path = tmp_path / "t.jsonl"
        write_transcript(path, [caveat_entry(), command_name_entry(), stdout_entry(REAL_CONTEXT_STDOUT)])
        payload, is_clean = bot._scan_transcript_for_stdout(path, 0)
        assert is_clean is True
        assert payload.startswith("## Context Usage")

    def test_prefers_the_twin_over_the_ansi_panel(self, bot, tmp_path):
        path = tmp_path / "t.jsonl"
        write_transcript(path, [stdout_entry(REAL_ANSI_STDOUT), twin_entry(REAL_TWIN_MARKDOWN)])
        payload, is_clean = bot._scan_transcript_for_stdout(path, 0)
        assert is_clean is True
        assert payload == REAL_TWIN_MARKDOWN.strip()
        assert "\x1b[" not in payload

    def test_ansi_panel_without_twin_is_reported_unclean(self, bot, tmp_path):
        """The twin may still be mid-write — the caller gets to wait one beat."""
        path = tmp_path / "t.jsonl"
        write_transcript(path, [stdout_entry(REAL_ANSI_STDOUT)])
        payload, is_clean = bot._scan_transcript_for_stdout(path, 0)
        assert is_clean is False
        assert "Context Usage" in payload

    def test_output_before_the_baseline_is_invisible(self, bot, tmp_path):
        """SCOPE GUARD: a /context run at the desk must never be picked up."""
        path = tmp_path / "t.jsonl"
        entries = [caveat_entry(), command_name_entry(), stdout_entry(REAL_CONTEXT_STDOUT)]
        write_transcript(path, entries)
        payload, is_clean = bot._scan_transcript_for_stdout(path, len(entries))
        assert payload is None
        assert is_clean is False

    def test_twin_beyond_the_lookahead_is_not_adopted(self, bot, tmp_path):
        """A later command's meta entry must not be mistaken for this one's output."""
        path = tmp_path / "t.jsonl"
        filler = {"type": "file-history-snapshot"}
        write_transcript(
            path,
            [stdout_entry(REAL_ANSI_STDOUT), filler, filler, filler, filler, twin_entry("## Something Else")],
        )
        payload, _ = bot._scan_transcript_for_stdout(path, 0)
        assert "Something Else" not in payload

    def test_empty_transcript_yields_nothing(self, bot, tmp_path):
        path = tmp_path / "t.jsonl"
        path.write_text("", encoding="utf-8")
        assert bot._scan_transcript_for_stdout(path, 0) == (None, False)

    def test_malformed_lines_are_skipped(self, bot, tmp_path):
        path = tmp_path / "t.jsonl"
        path.write_text("not json\n" + json.dumps(stdout_entry(REAL_CONTEXT_STDOUT)) + "\n", encoding="utf-8")
        payload, _ = bot._scan_transcript_for_stdout(path, 0)
        assert payload.startswith("## Context Usage")

    def test_unreadable_transcript_yields_nothing(self, bot, tmp_path):
        assert bot._scan_transcript_for_stdout(tmp_path / "gone.jsonl", 0) == (None, False)


# =============================================
# 3. TELEGRAM FORMATTING
# =============================================


class TestFormatting:
    """Markdown tables only survive Telegram inside a monospace block."""

    def test_wraps_in_pre_block(self, bot):
        out = bot._format_stdout_for_telegram("plain")
        assert out == "<pre>plain</pre>"

    def test_strips_ansi_escapes(self, bot):
        out = bot._format_stdout_for_telegram("\x1b[1mBold\x1b[22m")
        assert "\x1b[" not in out
        assert "Bold" in out

    def test_escapes_html_significant_characters(self, bot):
        out = bot._format_stdout_for_telegram("a & b <tag> c")
        assert "&amp;" in out and "&lt;tag&gt;" in out
        # Only the wrapper's own angle brackets remain unescaped
        assert out.count("<") == 2 and out.count(">") == 2

    def test_ampersand_escaped_before_angle_brackets(self, bot):
        """Escaping in the wrong order would double-escape into &amp;lt;."""
        assert bot._format_stdout_for_telegram("<") == "<pre>&lt;</pre>"

    def test_real_context_payload_survives_formatting(self, bot):
        payload = REAL_CONTEXT_STDOUT.split("<local-command-stdout>")[1].split("</local-command-stdout>")[0]
        out = bot._format_stdout_for_telegram(payload)
        assert out.startswith("<pre>") and out.endswith("</pre>")
        assert "| System prompt | 5.6k | 1.6% |" in out


class TestSendStdoutPanel:
    """Chunking must not split a <pre> across two messages."""

    def test_sends_single_block_with_html_parse_mode(self, bot):
        bot._send_stdout_panel(999, "## Context Usage")
        assert bot.send_message.call_count == 1
        args, kwargs = bot.send_message.call_args
        assert args[0] == 999
        assert args[1] == "<pre>## Context Usage</pre>"
        assert kwargs["parse_mode"] == "HTML"

    def test_long_output_is_chunked_and_each_chunk_is_a_complete_block(self, bot):
        bot._send_stdout_panel(999, "\n".join(f"| row {i} | value |" for i in range(600)))
        assert bot.send_message.call_count > 1
        for call in bot.send_message.call_args_list:
            text = call.args[1]
            assert text.startswith("<pre>") and text.endswith("</pre>")
            assert len(text) <= 4096
            assert call.kwargs["parse_mode"] == "HTML"

    def test_ansi_stripped_before_chunking(self, bot):
        bot._send_stdout_panel(999, "\x1b[1mContext Usage\x1b[22m")
        assert "\x1b[" not in bot.send_message.call_args.args[1]


class TestSendMessageParseMode:
    """The new parameter must stay opt-in — agent replies are plain text."""

    def test_parse_mode_omitted_by_default(self, tmp_path):
        workdir = tmp_path / "w"
        workdir.mkdir()
        with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.PENDING_DIR", tmp_path):
            plain = BaseBot(bot_id="p", bot_token="1:T", work_dir=workdir, bot_name="P", allowed_user_ids=[])
        with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.urlopen") as mock_open:
            mock_open.return_value.__enter__.return_value.read.return_value = b'{"ok":true,"result":{}}'
            plain.send_message(1, "hello")
            payload = json.loads(mock_open.call_args.args[0].data.decode())
        assert "parse_mode" not in payload

    def test_parse_mode_included_when_given(self, tmp_path):
        workdir = tmp_path / "w"
        workdir.mkdir()
        with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.PENDING_DIR", tmp_path):
            plain = BaseBot(bot_id="p", bot_token="1:T", work_dir=workdir, bot_name="P", allowed_user_ids=[])
        with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.urlopen") as mock_open:
            mock_open.return_value.__enter__.return_value.read.return_value = b'{"ok":true,"result":{}}'
            plain.send_message(1, "<pre>x</pre>", parse_mode="HTML")
            payload = json.loads(mock_open.call_args.args[0].data.decode())
        assert payload["parse_mode"] == "HTML"


# =============================================
# 4. THE ALLOWLIST
# =============================================


class TestAllowlist:
    """Exact-match, config-overridable, and /cost deliberately absent."""

    def test_context_is_informational_by_default(self, bot):
        assert "context" in bot._informational_commands()
        assert DEFAULT_INFORMATIONAL_COMMANDS == ("context",)

    def test_informational_commands_pass_the_guard_unchanged(self, bot):
        assert bot._guard_slash_injection("/context") == "/context"

    def test_side_effect_commands_still_pass_the_guard(self, bot):
        for cmd in ("/clear", "/compact", "/prep", "/memo"):
            assert bot._guard_slash_injection(cmd) == cmd

    def test_cost_is_not_allowlisted(self, bot):
        """Its transcript shape was never observed, so it is not assumed to match."""
        assert "cost" not in bot._passthrough_commands()
        assert bot._guard_slash_injection("/cost") == " /cost"

    def test_unknown_slash_command_still_neutralised(self, bot):
        assert bot._guard_slash_injection("/nonsense") == " /nonsense"

    def test_config_can_override_the_informational_list(self, bot):
        with patch(
            "aipass.skills.lib.telegram.apps.handlers.config.load_bot_config",
            return_value={"informational_commands": ["/Cost", "context"]},
        ):
            assert bot._informational_commands() == {"cost", "context"}

    def test_config_failure_falls_back_to_defaults(self, bot):
        with patch(
            "aipass.skills.lib.telegram.apps.handlers.config.load_bot_config",
            side_effect=RuntimeError("boom"),
        ):
            assert bot._informational_commands() == {"context"}


# =============================================
# 5. NO-WEDGE COMPLETION
# =============================================


class TestNoWedge:
    """A local command produces no assistant turn — it must never leave a pending."""

    def test_informational_command_writes_no_pending_file(self, bot, tmp_path):
        transcript = tmp_path / "t.jsonl"
        write_transcript(transcript, [command_name_entry()])
        with patch.object(bot, "_resolve_active_transcript", return_value=(str(transcript), 1)):
            with patch.object(bot, "_relay_slash_stdout"):
                bot.handle_message(999, "/context", {"message_id": 7})
        assert not bot.pending_file.exists()

    def test_informational_command_starts_no_heartbeat(self, bot, tmp_path):
        transcript = tmp_path / "t.jsonl"
        write_transcript(transcript, [command_name_entry()])
        with patch.object(bot, "_resolve_active_transcript", return_value=(str(transcript), 1)):
            with patch.object(bot, "_start_heartbeat") as heartbeat:
                with patch.object(bot, "_relay_slash_stdout"):
                    bot.handle_message(999, "/context", {"message_id": 7})
        heartbeat.assert_not_called()

    def test_informational_command_is_injected_verbatim(self, bot, tmp_path):
        """A sender prefix would stop CC from running it as a command at all."""
        transcript = tmp_path / "t.jsonl"
        write_transcript(transcript, [command_name_entry()])
        with patch.object(bot, "_resolve_active_transcript", return_value=(str(transcript), 1)):
            with patch.object(bot, "_relay_slash_stdout"):
                bot.handle_message(999, "/context", {"message_id": 7})
        bot.inject_message.assert_called_once_with("/context")

    def test_missing_transcript_reports_honestly_and_injects_nothing(self, bot):
        with patch.object(bot, "_resolve_active_transcript", return_value=(None, 0)):
            bot.handle_message(999, "/context", {"message_id": 7})
        bot.inject_message.assert_not_called()
        assert "no active claude transcript" in bot.send_message.call_args.args[1].lower()

    def test_side_effect_command_behaviour_is_unchanged(self, bot):
        """clear/compact/prep/memo keep the pending-file flow exactly."""
        with patch.object(bot, "_start_heartbeat"):
            bot.handle_message(999, "/clear", {"message_id": 7})
        assert bot.pending_file.exists()
        bot.inject_message.assert_called_once_with("/clear")

    def test_normal_message_behaviour_is_unchanged(self, bot):
        with patch.object(bot, "_start_heartbeat"):
            bot.handle_message(999, "hello there", {"message_id": 7})
        assert bot.pending_file.exists()
        bot.inject_message.assert_called_once_with("hello there")

    def test_normal_message_starts_no_relay_watcher(self, bot):
        """SCOPE GUARD: only an injected informational command may watch stdout."""
        with patch.object(bot, "_start_heartbeat"):
            bot.handle_message(999, "hello there", {"message_id": 7})
        assert bot._slash_stdout_thread is None

    def test_failed_injection_reports_and_starts_no_watcher(self, bot, tmp_path):
        transcript = tmp_path / "t.jsonl"
        write_transcript(transcript, [command_name_entry()])
        bot.inject_message.return_value = False
        with patch.object(bot, "_resolve_active_transcript", return_value=(str(transcript), 1)):
            bot.handle_message(999, "/context", {"message_id": 7})
        assert bot._slash_stdout_thread is None
        assert not bot.pending_file.exists()
        bot.edit_message.assert_called_once()
        assert "failed" in bot.edit_message.call_args.args[2].lower()


class TestRelayLoop:
    """The relay owns its own completion: it always finishes, one way or another."""

    def test_relays_the_payload_and_clears_the_placeholder(self, bot, tmp_path):
        transcript = tmp_path / "t.jsonl"
        write_transcript(transcript, [stdout_entry(REAL_CONTEXT_STDOUT)])
        with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.SLASH_STDOUT_POLL_INTERVAL", 0):
            bot._relay_slash_stdout(999, "context", transcript, 0, 42)
        bot.edit_message.assert_called_once_with(999, 42, "/context")
        sent = bot.send_message.call_args.args[1]
        assert sent.startswith("<pre>") and "| System prompt | 5.6k | 1.6% |" in sent

    def test_waits_one_extra_poll_for_the_markdown_twin(self, bot, tmp_path):
        """The ANSI panel lands first; the clean twin is a beat behind it."""
        transcript = tmp_path / "t.jsonl"
        write_transcript(transcript, [stdout_entry(REAL_ANSI_STDOUT)])

        def land_the_twin(*args, **kwargs):
            write_transcript(transcript, [stdout_entry(REAL_ANSI_STDOUT), twin_entry(REAL_TWIN_MARKDOWN)])

        with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.SLASH_STDOUT_POLL_INTERVAL", 0):
            with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.time.sleep", side_effect=land_the_twin):
                bot._relay_slash_stdout(999, "context", transcript, 0, 42)
        sent = bot.send_message.call_args.args[1]
        assert "claude-opus-4-8" in sent
        assert "⛁" not in sent  # the box-drawing panel never reached the chat

    def test_relays_the_ansi_panel_rather_than_losing_it(self, bot, tmp_path):
        """If the twin never arrives, the stripped panel still beats silence."""
        transcript = tmp_path / "t.jsonl"
        write_transcript(transcript, [stdout_entry(REAL_ANSI_STDOUT)])
        with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.SLASH_STDOUT_POLL_INTERVAL", 0):
            bot._relay_slash_stdout(999, "context", transcript, 0, 42)
        assert "Context Usage" in bot.send_message.call_args.args[1]

    def test_timeout_reports_honestly_and_terminates(self, bot, tmp_path):
        transcript = tmp_path / "t.jsonl"
        write_transcript(transcript, [command_name_entry()])
        with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.SLASH_STDOUT_POLL_INTERVAL", 0):
            with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.SLASH_STDOUT_TIMEOUT_SECONDS", 0.05):
                bot._relay_slash_stdout(999, "context", transcript, 0, 42)
        bot.edit_message.assert_called_once()
        text = bot.edit_message.call_args.args[2]
        assert "/context" in text and "no output" in text.lower()

    def test_timeout_without_a_placeholder_still_reports(self, bot, tmp_path):
        transcript = tmp_path / "t.jsonl"
        write_transcript(transcript, [command_name_entry()])
        with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.SLASH_STDOUT_POLL_INTERVAL", 0):
            with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.SLASH_STDOUT_TIMEOUT_SECONDS", 0.05):
                bot._relay_slash_stdout(999, "context", transcript, 0, None)
        bot.edit_message.assert_not_called()
        assert "no output" in bot.send_message.call_args.args[1].lower()

    def test_timeout_is_bounded_by_the_constant(self, bot):
        assert 0 < SLASH_STDOUT_TIMEOUT_SECONDS <= 300

    def test_stale_output_before_the_baseline_never_reaches_the_chat(self, bot, tmp_path):
        """SCOPE GUARD, end to end: a desk-run /context times out, it does not echo."""
        transcript = tmp_path / "t.jsonl"
        write_transcript(transcript, [stdout_entry(REAL_CONTEXT_STDOUT)])
        with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.SLASH_STDOUT_POLL_INTERVAL", 0):
            with patch("aipass.skills.lib.telegram.apps.handlers.base_bot.SLASH_STDOUT_TIMEOUT_SECONDS", 0.05):
                bot._relay_slash_stdout(999, "context", transcript, 1, 42)
        bot.send_message.assert_not_called()
        assert "no output" in bot.edit_message.call_args.args[2].lower()


def test_ansi_regex_matches_real_escapes():
    """Guard the regex itself — it is the only thing standing between TUI art and the chat."""
    assert ANSI_ESCAPE_RE.sub("", "\x1b[38;5;244m⛁\x1b[39m") == "⛁"
    assert ANSI_ESCAPE_RE.sub("", "no escapes here") == "no escapes here"
