# =================== META ====================
# Name: test_declared_pass_symbol_resolves_check.py
# Description: declared_pass_symbol_resolves_check — a declared-pass name that resolves nowhere
# Version: 1.0.0
# Created: 2026-09-25
# Modified: 2026-09-25
# =============================================

"""Tests for apps/handlers/aipass_standards/declared_pass_symbol_resolves_check.py."""

# The declared pass — what is NOT tested here, and what covers it instead:
# seedgo: no-test-needed(shared) — is_bypassed's own matching rules; tests/test_bypass.py
# seedgo: no-test-needed(shared) — H1 and H2 on the same lines; tests/test_declared_pass_contradiction_check.py

from pathlib import Path

from aipass.seedgo.apps.handlers.aipass_standards import declared_pass_symbol_resolves_check as checker

#: The model file for the whole per-item series.
MODEL = Path(__file__).resolve().parent / "test_readme_update.py"

#: What @backup's ceiling handler does with the filesystem: getsize, never scandir.
PRODUCT = "import os\n\n\ndef total(path):\n    return os.path.getsize(path)\n"


def _branch(tmp_path, declared, product=PRODUCT, imports=""):
    """A branch tree the rule can resolve: apps/ to read, tests/ to judge."""
    apps = tmp_path / "apps"
    (apps / "handlers" / "scan").mkdir(parents=True, exist_ok=True)
    (apps / "handlers" / "scan" / "ceiling.py").write_text(product, encoding="utf-8")
    tests = tmp_path / "tests"
    tests.mkdir(exist_ok=True)
    path = tests / "test_specimen.py"
    path.write_text(f'"""Tests."""\n{declared}\n{imports}\n', encoding="utf-8")
    checker.product_facts.cache_clear()
    return path


def _verdict(path):
    """(score, the one check's message) for a planted file."""
    result = checker.check_module(str(path))
    return result["score"], result["checks"][0]["message"]


class TestTheModelFilePasses:
    """The template's own model is the floor: if it fails, the rule is wrong."""

    def test_every_name_the_model_declares_resolves(self):
        assert checker.check_module(str(MODEL))["score"] == 100


class TestThePlantedSpecimens:
    """The 2026-09-24 review of @backup's tests: three lines that declare a pass on nothing."""

    def test_a_stdlib_call_the_product_never_makes_is_convicted(self, tmp_path):
        """test_ceiling_guard.py:15 — os.scandir; the product calls only getsize."""
        path = _branch(tmp_path, "# seedgo: no-test-needed(stdlib) — os.path.getsize() and os.scandir() behavior")
        score, message = _verdict(path)
        assert score == 0
        assert "declares os.scandir needs no test, but it is stdlib, but the product never uses it" in message
        assert "getsize" not in message

    def test_the_tests_own_helper_named_as_product_is_convicted(self, tmp_path):
        """test_ceiling_guard.py:16 — _project is the test file's fixture, not product."""
        path = _branch(tmp_path, "# seedgo: no-test-needed(generated) — the file tree generated by _project fixtures")
        score, message = _verdict(path)
        assert score == 0
        assert "declares _project needs no test, but it names nothing in apps/" in message

    def test_a_line_that_names_nothing_is_convicted(self, tmp_path):
        """test_snapshot_fidelity.py:14 — no name at all, and no size threshold exists."""
        path = _branch(tmp_path, "# seedgo: no-test-needed(constant) — dryrun mode and file size thresholds")
        score, message = _verdict(path)
        assert score == 0
        assert "declares (constant) needs no test, but it names nothing at all" in message

    def test_a_library_declared_as_stdlib_is_convicted(self, tmp_path):
        """test_handlers_filesystem.py:15 — pathspec is a library, not the standard library."""
        path = _branch(tmp_path, "# seedgo: no-test-needed(stdlib) — os, pathlib, pathspec, shutil usage")
        score, message = _verdict(path)
        assert score == 0
        assert "declares pathspec needs no test, but it is not a stdlib name" in message


class TestWhatResolves:
    def test_a_private_name_the_product_defines_resolves(self, tmp_path):
        product = PRODUCT + "\n\ndef _project():\n    return None\n"
        path = _branch(tmp_path, "# seedgo: no-test-needed(generated) — trees from _project", product=product)
        assert _verdict(path)[0] == 100

    def test_a_line_whose_category_is_a_pack_standard_may_carry_prose(self, tmp_path):
        path = _branch(tmp_path, "# seedgo: no-test-needed(documentation) — handler functions carry docstrings")
        assert _verdict(path)[0] == 100

    def test_a_misspelt_stdlib_chain_is_not_a_stdlib_name(self, tmp_path):
        path = _branch(tmp_path, "# seedgo: no-test-needed(stdlib) — os.path.getsizes() behaviour")
        assert "declares os.path.getsizes needs no test, but it is not a real stdlib name" in _verdict(path)[1]

    def test_a_name_bound_by_a_stdlib_import_is_followed_through_it(self, tmp_path):
        product = "from datetime import datetime\n\nSTAMP = datetime.fromisoformat('2026-09-25')\n"
        path = _branch(tmp_path, "# seedgo: no-test-needed(stdlib) — datetime.fromisoformat parsing", product=product)
        assert _verdict(path)[0] == 100

    def test_a_submodule_head_resolves_through_the_test_files_own_import(self, tmp_path):
        declared = "# seedgo: no-test-needed(stdlib) — mock.patch behavior"
        imports = "from unittest.mock import patch"
        score, message = _verdict(_branch(tmp_path, declared, imports=imports))
        assert score == 0
        assert "declares mock.patch needs no test, but it is stdlib, but the product never uses it" in message

    def test_a_bare_call_is_looked_up_on_the_stdlib_module_the_line_names(self, tmp_path):
        product = "from pathlib import Path\n\n\ndef where(p):\n    return Path(p).resolve()\n"
        path = _branch(tmp_path, "# seedgo: no-test-needed(stdlib) — pathlib's resolve() behaviour", product=product)
        assert _verdict(path)[0] == 100

    def test_a_path_resolves_when_apps_has_it_and_is_convicted_when_not(self, tmp_path):
        declared = "# seedgo: no-test-needed(ruff) — that scan/ceiling.py and handlers/nowhere/ parse"
        score, message = _verdict(_branch(tmp_path, declared))
        assert score == 0
        assert "declares handlers/nowhere/ needs no test, but it is no directory or module in apps/" in message
        assert "ceiling" not in message


class TestWhatIsNeverJudgedHere:
    def test_an_either_or_of_two_words_is_prose_not_a_path(self, tmp_path):
        path = _branch(tmp_path, "# seedgo: no-test-needed(shared) — the production/tests split; tests/test_x.py")
        assert _verdict(path)[0] == 100

    def test_an_absent_snake_case_call_is_left_to_h2(self, tmp_path):
        path = _branch(tmp_path, "# seedgo: no-test-needed(documentation) — that resolve_caller_path() has one")
        assert _verdict(path)[0] == 100

    def test_a_file_with_no_declared_pass_passes(self, tmp_path):
        path = _branch(tmp_path, "")
        assert _verdict(path) == (100, "Every name the declared pass mentions resolves")
