# =================== AIPass ====================
# Name: declared_pass_symbol_resolves_check.py
# Description: Declared Pass Symbol Resolves Standards Checker Handler
# Version: 1.0.0
# Created: 2026-09-25
# Modified: 2026-09-25
# =============================================

"""
Declared Pass Symbol Resolves Standards Checker Handler

The third shape of a broken declared pass, after the two
``declared_pass_contradiction`` scores (H1 literal-asserted, H2 an UPPER or
snake_case name absent from ``apps/``): the WRONG SYMBOL. A
``# seedgo: no-test-needed(<kind>) -- <prose>`` line names things, and a line
whose names resolve nowhere is a declared pass on nothing.

  ``test_ceiling_guard.py:15`` declares ``os.scandir()`` behaviour untested;
  nothing in @backup's ``apps/`` ever calls ``scandir``.
  ``test_ceiling_guard.py:16`` declares the tree ``generated by _project
  fixtures``; ``_project`` is the test file's own helper, not product.
  ``test_snapshot_fidelity.py:14`` declares ``dryrun mode and file size
  thresholds``: no name at all, and no file-size threshold exists.

WHAT IS AN IDENTIFIER. Plain English words are not. The rule reads five shapes
out of the prose: a dotted name (``os.path.getsize``), a name ending in ``()``,
an ``_``-prefixed name, a CamelCase name, and a slash path (``handlers/readme/``,
a module path). On a ``(stdlib)`` line a bare word that is an importable module
(``shutil``, ``pathspec``) is one too, because that line's whole claim is "this
module". A bare UPPER or snake_case name is H2's and is not judged twice here.

WHAT RESOLVES.
  * A name whose head is a stdlib module, or a name the branch imports from
    one (``Path``), resolves when the attribute chain is real AND the branch's
    product uses its last segment. A real stdlib call the product never makes
    is a declaration about somebody else's code.
  * On a ``(stdlib)`` line, a name that is not stdlib is the finding
    (``pathspec`` is a library).
  * Anything else resolves when its last segment appears as a word in the
    branch's ``apps/`` source text -- the text, not the AST, for the reason H2
    records: env-var strings, dataclass fields and path segments are real uses.
  * A slash path resolves when ``apps/`` has that directory or module.

A LINE THAT NAMES NOTHING is its own finding -- unless its category is itself
a standard in this pack (``ruff``, ``documentation``, ``cli``). Then the line
points at the checker that covers it, which is the declaration resolving, and
its prose is scope, not a symbol. The template's own model file carries exactly
that line (``documentation -- that the public generator functions carry
docstrings``), and the model is the floor.

A ``covered-elsewhere`` reference (``tests/test_bypass.py``) names the file that
does the covering and is never judged.
"""

import ast
import importlib
import importlib.util
import re
import sys
from functools import lru_cache
from pathlib import Path
from typing import Dict, FrozenSet, List, Set, Tuple

from aipass.prax import logger
from aipass.seedgo.apps.handlers.bypass.utils import is_bypassed
from aipass.seedgo.apps.handlers.json import json_handler

APPLIES_TO = "tests"
AUDIT_SCOPE = "all_files"

STANDARD = "DECLARED_PASS_SYMBOL_RESOLVES"
STANDARD_KEY = "declared_pass_symbol_resolves"

#: The declared-pass line test template v1 item 7 asks every test file to carry.
DECLARED = re.compile(r"#\s*seedgo:\s*no-test-needed\(([\w-]+)\)\s*(?:[-–—]+)?\s*(.*)")

#: The category whose claim is "this is the standard library's behaviour".
STDLIB = "stdlib"

#: The five identifier shapes a declaration's prose can carry.
DOTTED = re.compile(r"(?<![\w./])([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)+)(?:\(\))?")
CALLED = re.compile(r"(?<![\w./])([A-Za-z_]\w*)\(\)")
PRIVATE = re.compile(r"(?<![\w./])(_[A-Za-z]\w*)")
CAMEL = re.compile(r"(?<![\w./])([A-Z][a-z0-9]+(?:[A-Z][a-z0-9]*)+)\b")
SLASHED = re.compile(r"(?<![\w./])([\w.-]+/(?:[\w.-]+/?)*)")

#: A bare word, read as a module name on a (stdlib) line only.
WORD = re.compile(r"(?<![\w./])([a-z][a-z0-9_]*)\b")

#: H2's two shapes (declared_pass_contradiction): a bare name in either is judged there.
H2_UPPER = re.compile(r"[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+|[A-Z]{3,}")
H2_SNAKE = re.compile(r"_?[a-z][a-z0-9]*(?:_[a-z0-9]+)+")

#: Covered-elsewhere references name a test file, not a symbol under test.
ELSEWHERE = ("test_", "tests/")

#: Where this pack's checkers live: a category that names one is a reference to it.
#: Never resolve()d at import: that reads the working directory, and an import
#: must not need one (tests/test_import_dead_cwd.py).
PACK_DIR = Path(__file__).parent

CURE = "name the symbol the product has, or drop the line"


def declarations(source: str) -> List[Tuple[int, str, str]]:
    """(line, category, prose) for every declared-pass line in this file."""
    found: List[Tuple[int, str, str]] = []
    for line, text in enumerate(source.splitlines(), 1):
        match = DECLARED.match(text.strip())
        if match:
            found.append((line, match.group(1), match.group(2)))
    return found


def _is_path_shaped(token: str) -> bool:
    """Whether a slashed token is a path, not an either/or of two words.

    ``handlers/readme/``, ``copy/snapshot.py`` and ``a/b/c`` are paths;
    ``production/tests`` is prose for "production or tests", and 22 seedgo
    declarations say exactly that.
    """
    return token.endswith("/") or token.endswith(".py") or token.count("/") >= 2


def _judged_by_h2(token: str) -> bool:
    """Whether declared_pass_contradiction already judges this bare name."""
    return H2_UPPER.fullmatch(token) is not None or H2_SNAKE.fullmatch(token) is not None


def identifiers(prose: str) -> Tuple[List[str], bool]:
    """(names this rule judges, whether the line names anything at all).

    The second answer counts H2's names too: a line whose only name is H2's
    names something, and whether that something exists is H2's verdict.
    """
    judged: List[str] = []
    named = False
    for rule in (SLASHED, DOTTED, CALLED, PRIVATE, CAMEL):
        for raw in rule.findall(prose):
            token = raw.rstrip(".") if rule is SLASHED else raw.rstrip("/.")
            if not token or token.startswith(ELSEWHERE):
                continue
            if rule is SLASHED and not _is_path_shaped(token):
                continue
            named = True
            if rule is not SLASHED and "." not in token and _judged_by_h2(token):
                continue
            inside_dotted = any(token in seen.split(".") for seen in judged if "." in seen)
            if token not in judged and not inside_dotted:
                judged.append(token)
    named = named or any(_judged_by_h2(word) for word in re.findall(r"\b\w+\b", prose))
    return judged, named


@lru_cache(maxsize=1)
def pack_standards() -> FrozenSet[str]:
    """Every standard this pack scores, by the name a category would use."""
    return frozenset(path.name[: -len("_check.py")] for path in PACK_DIR.glob("*_check.py"))


def _branch_root(path: Path) -> Path | None:
    """The branch a test file lives in: the parent of its ``tests/`` directory."""
    for parent in path.resolve().parents:
        if (parent / "tests").is_dir() and (parent / "apps").is_dir():
            return parent
    return None


def _is_stdlib(module: str) -> bool:
    """Whether a dotted module name belongs to the standard library."""
    return module.split(".")[0] in sys.stdlib_module_names


def stdlib_anchors(tree: ast.AST) -> Dict[str, Tuple[str, bool]]:
    """What a declared head can mean, from one file's stdlib imports.

    ``from pathlib import Path`` makes ``Path.resolve`` followable from
    pathlib; ``from unittest.mock import patch`` makes ``mock.patch``
    followable, because ``mock`` is that module's own last segment.
    """
    anchors: Dict[str, Tuple[str, bool]] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module and _is_stdlib(node.module):
            # The imported NAME wins over the module's own last segment: after
            # ``from datetime import datetime`` the head is the class. A
            # top-level module is still tried as a module by _stdlib_chain.
            for alias in node.names:
                anchors.setdefault(alias.asname or alias.name, (node.module, False))
            anchors.setdefault(node.module.split(".")[-1], (node.module, True))
        elif isinstance(node, ast.Import):
            stdlib = (alias for alias in node.names if _is_stdlib(alias.name))
            for alias in stdlib:
                anchors.setdefault(alias.asname or alias.name.split(".")[-1], (alias.name, True))
    return anchors


def _parse(source: str, where: object) -> ast.Module | None:
    """A file's tree, or None when Python cannot read it (``ruff`` convicts that)."""
    try:
        return ast.parse(source)
    except SyntaxError as exc:
        logger.info("[declared_pass_symbol_resolves] Unparseable %s: %s", where, exc)
        return None


@lru_cache(maxsize=64)
def product_facts(branch_root: Path) -> Tuple[str, FrozenSet[str], Dict[str, Tuple[str, bool]]]:
    """(apps/ source text, every apps/ dir and module path, the product's stdlib anchors).

    The text answers "does the product use this name": an env-var string, a
    dataclass field and a path segment are all uses the AST's names miss.
    """
    apps = branch_root / "apps"
    chunks: List[str] = []
    paths: Set[str] = set()
    anchors: Dict[str, Tuple[str, bool]] = {}
    for path in sorted(apps.rglob("*")):
        if "__pycache__" in path.parts:
            continue
        rel = path.relative_to(apps).as_posix()
        paths.add(rel[: -len(".py")] if rel.endswith(".py") else rel)
        if path.suffix != ".py" or not path.is_file():
            continue
        source = _read(path)
        if source is None:
            continue
        chunks.append(source)
        tree = _parse(source, path)
        if tree is not None:
            for name, anchor in stdlib_anchors(tree).items():
                anchors.setdefault(name, anchor)
    return "\n".join(chunks), frozenset(paths), anchors


def _mentions(name: str, text: str) -> bool:
    """Whether the branch's product source mentions this name as a word."""
    return re.search(r"(?<!\w)" + re.escape(name) + r"(?!\w)", text) is not None


@lru_cache(maxsize=256)
def _module(name: str) -> object | None:
    """A stdlib module, imported, or None when it will not import."""
    try:
        return importlib.import_module(name)
    except ImportError as exc:
        logger.info("[declared_pass_symbol_resolves] Cannot import %s: %s", name, exc)
        return None


def _walk(obj: object, parts: List[str]) -> bool:
    """Whether every attribute in the chain exists on the object before it."""
    for part in parts:
        if not hasattr(obj, part):
            return False
        obj = getattr(obj, part)
    return True


def _stdlib_chain(token: str, anchors: Dict[str, Tuple[str, bool]]) -> bool | None:
    """Whether a declared name is a real stdlib name; None when its head is not stdlib.

    A head can mean two things at once: ``datetime`` is a module, and after
    ``from datetime import datetime`` it is also the class. The name is real
    when either reading walks.
    """
    parts = token.split(".")
    readings: List[Tuple[str, bool]] = []
    if _is_stdlib(parts[0]):
        readings.append((parts[0], True))
    if parts[0] in anchors:
        readings.append(anchors[parts[0]])
    if not readings:
        return None
    for module_name, head_is_module in readings:
        module = _module(module_name)
        if module is not None and _walk(module, parts[1:] if head_is_module else parts):
            return True
    return False


@lru_cache(maxsize=512)
def _member_of(module_name: str, name: str) -> bool:
    """Whether a stdlib module, or a public class in it, has this attribute."""
    module = _module(module_name)
    if module is None:
        return False
    if hasattr(module, name):
        return True
    classes = (getattr(module, attr) for attr in dir(module) if attr[:1].isupper())
    return any(isinstance(cls, type) and hasattr(cls, name) for cls in classes)


@lru_cache(maxsize=512)
def _is_library(word: str) -> bool:
    """Whether a bare word is an installed third-party top-level module."""
    if _is_stdlib(word):
        return False
    try:
        spec = importlib.util.find_spec(word)
    except (ImportError, ValueError) as exc:
        logger.info("[declared_pass_symbol_resolves] No spec for %s: %s", word, exc)
        return False
    origin = str(getattr(spec, "origin", "") or "") if spec else ""
    return "site-packages" in origin or "dist-packages" in origin


def _path_exists(token: str, paths: FrozenSet[str]) -> bool:
    """Whether apps/ has this directory or module, matched as a path suffix."""
    bare = token.strip("/")
    bare = bare[: -len(".py")] if bare.endswith(".py") else bare
    bare = re.sub(r"^(?:src/)?(?:aipass/)?(?:\w+/)?apps/", "", bare)
    return any(rel == bare or rel.endswith("/" + bare) for rel in paths)


def judge(
    token: str,
    category: str,
    text: str,
    paths: FrozenSet[str],
    anchors: Dict[str, Tuple[str, bool]],
    modules: List[str],
) -> str | None:
    """What is wrong with one declared name, or None when it resolves.

    ``modules`` are the stdlib modules the same line names, which is where a
    bare ``resolve()`` on "pathlib's resolve()" is looked up.
    """
    if "/" in token:
        return None if _path_exists(token, paths) else "is no directory or module in apps/"
    last = token.split(".")[-1]
    real = _stdlib_chain(token, anchors)
    if real is None and "." not in token and category == STDLIB:
        real = True if any(_member_of(module, token) for module in modules) else None
    if real is False:
        return "is not a real stdlib name"
    if real:
        return None if _mentions(last, text) else "is stdlib, but the product never uses it"
    if category == STDLIB:
        return "is not a stdlib name"
    return None if _mentions(last, text) else "names nothing in apps/"


def scan(source: str, branch_root: Path | None) -> List[Tuple[int, str, str]]:
    """(line, name, what is wrong) for every declared name that resolves nowhere."""
    declared = declarations(source)
    if not declared or branch_root is None:
        return []
    tree = _parse(source, "test file")
    if tree is None:
        return []
    text, paths, product_anchors = product_facts(branch_root)
    anchors = {**stdlib_anchors(tree), **product_anchors}
    found: List[Tuple[int, str, str]] = []
    for line, category, prose in declared:
        tokens, named = identifiers(prose)
        modules: List[str] = []
        if category == STDLIB:
            for word in WORD.findall(prose):
                if _is_stdlib(word):
                    modules.append(word)
                if (_is_stdlib(word) or _is_library(word)) and word not in tokens:
                    tokens.append(word)
        if not named and not tokens:
            if category.replace("-", "_") not in pack_standards():
                found.append((line, f"({category})", f"names nothing at all - {CURE}"))
            continue
        for token in tokens:
            why = judge(token, category, text, paths, anchors, modules)
            if why:
                found.append((line, token, f"{why} - {CURE}"))
    return found


def _read(path: Path) -> str | None:
    """A file's text, or None if it cannot be read."""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError as exc:
        logger.info("[declared_pass_symbol_resolves] Cannot read %s: %s", path, exc)
        return None


def _result(passed: bool, checks: List[Dict], score: int) -> Dict:
    """The result shape every checker in this pack returns."""
    return {"passed": passed, "checks": checks, "score": score, "standard": STANDARD}


def _one_check(passed: bool, message: str) -> List[Dict]:
    """A single-entry checks list, for the paths that have one thing to say."""
    return [{"name": "Declared pass symbol resolves", "passed": passed, "message": message}]


def check_module(module_path: str, bypass_rules: list | None = None) -> Dict:
    """Check that every name a test file's declared pass mentions exists.

    Args:
        module_path: Path to the file to check.
        bypass_rules: Optional bypass rules, applied per standard.

    Returns:
        dict: {'passed', 'checks', 'score', 'standard'} -- the pack's shape.
    """
    if is_bypassed(module_path, STANDARD_KEY, bypass_rules=bypass_rules):
        return _result(True, _one_check(True, "Standard bypassed via .seedgo/bypass.json"), 100)

    path = Path(module_path)
    if not path.exists():
        return _result(False, _one_check(False, f"File not found: {module_path}"), 0)

    source = _read(path)
    if source is None:
        return _result(False, _one_check(False, f"Error reading file: {module_path}"), 0)

    findings = scan(source, _branch_root(path))
    if not findings:
        return _result(True, _one_check(True, "Every name the declared pass mentions resolves"), 100)

    # Every hit on ONE check: checklist._format_failure prints the first failed
    # check and appends "(+N more)", so one check per name would hide the rest.
    detail = "\n".join(
        f"{path.name}:{line} declares {name} needs no test, but it {why}" for line, name, why in findings
    )

    json_handler.log_operation(
        "check_completed",
        {"file": str(module_path), "score": 0, "standard": STANDARD_KEY, "hits": len(findings)},
    )
    return _result(False, _one_check(False, detail), 0)
