# =================== AIPass ====================
# Name: help_flag_safety_content.py
# Description: Help-Flag Safety Standards Content Handler
# Version: 1.0.0
# Created: 2026-08-13
# Modified: 2026-08-13
# =============================================

"""
Help-Flag Safety Standards Content Handler

Provides formatted help-flag safety standards content.
Module orchestrates, handler implements.
"""

from aipass.seedgo.apps.handlers.json import json_handler


def get_help_flag_safety_standards() -> str:
    """Return formatted help-flag safety standards content with Rich markup

    Returns:
        str: Formatted standards text with Rich styling
    """
    lines = [
        "[bold red]A HELP FLAG ANYWHERE MEANS EXPLAIN, NEVER EXECUTE[/bold red]",
        "",
        "[yellow]THE RULE:[/yellow] If [dim]--help[/dim] or [dim]-h[/dim] appears at ANY position in the",
        "  arguments, the command describes itself. It does not run.",
        "",
        "─" * 70,
        "",
        "[bold cyan]WHAT WENT WRONG (2026-08-13):[/bold cyan]",
        "",
        "  Every branch probed read the help flag at ONE fixed position, almost",
        "  always [dim]args[0][/dim]. A flag any later on the line was discarded and the",
        "  subcommand ran instead.",
        "",
        "  [red]drone @memory rollover push --help[/red]",
        "    [dim]-> args = ['push', '--help'], args[0] == 'push'[/dim]",
        "    [dim]-> gate misses, push() runs[/dim]",
        "    [red]-> PERFORMED the fleet-wide per_branch reset it was asked to describe[/red]",
        "",
        "  [yellow]One morning of this shape cost:[/yellow]",
        "    a 17-branch config reset, a real backup run, a real data cleanup,",
        "    an enrollment write. Near-misses: an external dev.to publish, and",
        "    an agent literally named [dim]--help[/dim].",
        "",
        "─" * 70,
        "",
        "[bold cyan]THE FIVE SHAPES:[/bold cyan]",
        "",
        "  [bold](a) MODULE GATE reading args[0] only[/bold]  [red](flagged)[/red]",
        '  [dim]    if args[0] in ("--help", "-h"):     # `push --help` slips past[/dim]',
        "",
        "  [bold](b) ROUTER intercepting remaining[0] only[/bold]  [yellow](precondition)[/yellow]",
        '  [dim]    if remaining[0] in ("--help", "-h"): # same bug, one layer up[/dim]',
        "",
        "  [bold](c) FLAG CONSUMED AS A VALUE[/bold]  [yellow](reported with (a))[/yellow]",
        "  [dim]    name = args[1]                      # creates an agent named --help[/dim]",
        "",
        "  [bold](d) SUBCOMMAND WORD OCCUPIES THE GATED SLOT[/bold]  [red](flagged)[/red]",
        '  [dim]    if args[0] == "scan":               # `scan --help` -> args[1], unread[/dim]',
        "  [dim]        scan_plan_files()               # ...and the verb runs anyway[/dim]",
        "",
        "  [bold](e) NO GATE AT ALL — args is NEVER read[/bold]  [red](flagged)[/red]",
        '  [dim]    if command == "demo":               # `demo --help` -> args=["--help"][/dim]',
        "  [dim]        run_demo()                      # ...never looked at, verb runs[/dim]",
        "  [dim]    Reported by @cli. The router DID rewrite remaining to ['--help'];[/dim]",
        "  [dim]    a module that ignores args cannot be saved by rewriting them.[/dim]",
        "  [dim]    Fleet population when the arm shipped: 0 of 152 modules.[/dim]",
        "",
        "─" * 70,
        "",
        "[bold cyan]HOW TO PASS — any ONE of these:[/bold cyan]",
        "",
        "  [green]✓[/green] [bold]Membership scan[/bold]",
        '  [dim]    if "--help" in args:[/dim]',
        "  [dim]        print_help()[/dim]",
        "  [dim]        return True[/dim]",
        "",
        "  [green]✓[/green] [bold]Comprehension scan[/bold]",
        '  [dim]    if any(a in ("--help", "-h") for a in args):[/dim]',
        "  [dim]        print_help()[/dim]",
        "  [dim]        return True[/dim]",
        "",
        "  [green]✓[/green] [bold]Shared helper[/bold] [dim](the @memory reference fix)[/dim]",
        "  [dim]    from ...handlers.cli.help_flags import wants_help[/dim]",
        "  [dim]    if wants_help(command, args):        # bare_help=False if you own `help`[/dim]",
        "  [dim]        print_help()[/dim]",
        "  [dim]        return True[/dim]",
        "",
        "  [green]✓[/green] [bold]argparse[/bold] — [dim]parse_known_args[/dim] absorbs the flag anywhere",
        "",
        "  [green]✓[/green] [bold]Router normalisation[/bold] [dim](the @backup reference fix)[/dim]",
        "  [dim]    # in apps/{branch}.py main(), BEFORE dispatch:[/dim]",
        '  [dim]    if any(arg in ("--help", "-h") for arg in remaining):[/dim]',
        "  [dim]        for module in modules:[/dim]",
        '  [dim]            if module.handle_command(command, ["--help"]):[/dim]',
        "  [dim]                return 0[/dim]",
        "",
        "─" * 70,
        "",
        "[bold cyan]TWO PLACES TO FIX, ONE IS ENOUGH:[/bold cyan]",
        "",
        "  [bold]Router[/bold]  — scan [dim]remaining[/dim], rewrite to [dim]['--help'][/dim], then delegate.",
        "            Protects every module behind it in one edit — but ONLY the",
        "            modules the router is the only way into. A module carrying",
        "            [dim]if __name__ == '__main__': handle_command(CMD, sys.argv[1:])[/dim]",
        "            is still reachable with raw argv and is scored on its own gate.",
        "            It cannot cover shape (e) at all: a module that never reads",
        "            [dim]args[/dim] discards the rewritten list along with everything else.",
        "            [dim]Reference: @backup, @aipass, @daemon[/dim]",
        "",
        "  [bold]Module[/bold]  — scan [dim]args[/dim] inside [dim]handle_command()[/dim].",
        "            Protects the module however it is reached.",
        "            [dim]Reference: @memory, @skills, @spawn[/dim]",
        "",
        "  [yellow]The checker accepts either. It fails only when NEITHER layer scans.[/yellow]",
        "",
        "─" * 70,
        "",
        "[bold cyan]WHAT IS NOT FLAGGED:[/bold cyan]",
        "",
        "  [green]✓[/green] A closed-vocabulary command — one that only ever compares",
        "    [dim]args[0][/dim] against literal subcommand names and takes no operands.",
        "    A stray flag has nowhere to hide, so a positional gate suffices.",
        "",
        "  [green]✓[/green] Arguments that only reach a logger or an error message.",
        "    Reporting an argument is not executing it.",
        "",
        "  [green]✓[/green] Entry points are read, never blamed — the router may legitimately",
        "    delegate help handling to the modules below it.",
        "",
        "[bold cyan]HONEST LIMIT:[/bold cyan]",
        "",
        "  [red]✗[/red] A routing function with NO help gate at all is not detected here —",
        "    outside [dim]handle_command[/dim]. 'No gate' is indistinguishable from 'not a",
        "    CLI surface' without heuristics that flood the fleet. [dim]subcommand_help[/dim]",
        "    covers the entry-point half of that gap.",
        "",
        "  [red]✗[/red] A [dim]handle_command[/dim] that READS [dim]args[/dim] but never gates on it. One read",
        "    leaves shape (e), and with no gate present the gate arms have nothing",
        "    to fire on. Closing that means guessing which read was meant to be a",
        "    gate — so it stays open, and stays stated.",
        "",
        "[bold cyan]SCOPE:[/bold cyan]",
        "  AUDIT_SCOPE = [bold]all_files[/bold]   [dim]— scored on apps/modules/*.py[/dim]",
        "  APPLIES_TO  = [bold]production[/bold]",
        "",
        "[bold cyan]REFERENCE:[/bold cyan]",
        "  [dim]See: seedgo standards pack (help_flag_safety)[/dim]",
        "  [dim]See: src/aipass/memory/apps/handlers/cli/help_flags.py[/dim]",
        "  [dim]See: src/aipass/backup/apps/backup.py (router normalisation)[/dim]",
    ]

    json_handler.log_operation("standard_content_queried", {"standard": "help_flag_safety"})
    return "\n".join(lines)
