# =================== AIPass ====================
# Name: rich_markup_content.py
# Description: Rich Markup Standards Content Handler
# Version: 1.0.0
# Created: 2026-08-11
# Modified: 2026-08-11
# =============================================

"""
Rich Markup Standards Content Handler

Provides formatted Rich Markup standards content.
Module orchestrates, handler implements.
"""

from aipass.seedgo.apps.handlers.json import json_handler


def get_rich_markup_standards() -> str:
    """Return formatted rich_markup standards content with Rich markup

    Returns:
        str: Formatted standards text with Rich styling
    """
    lines = [
        "[bold cyan]CORE PRINCIPLE:[/bold cyan]",
        "  Rich reads [dim]\\[word][/dim] in a printed string as a style tag.",
        "  When the tag is not a real Rich style, Rich [red]silently deletes it[/red]",
        "  from the rendered output -- no error, no gap, no marker.",
        "",
        "  Your source string is correct, so every source-reading audit passes",
        "  at 100% while the user reads mutilated output. That is what makes",
        "  this class of defect survive: it is invisible on both sides.",
        "",
        "[bold cyan]THE DEFECT -- RENDER-TIME LOSS:[/bold cyan]",
        '  [dim]console.print("drone @hooks <command> \\[args...]")[/dim]',
        "  renders as [red]drone @hooks <command>[/red]   <- the notation vanished from --help",
        "",
        '  [dim]console.print("monitor run \\[branches]")[/dim]',
        "  renders as [red]monitor run[/red]",
        "",
        '  [dim]console.print("\\[branch] row")[/dim]',
        "  renders as [red] row[/red]   <- a log tool lost its whole attribution column",
        "",
        "[bold cyan]WHAT IT CHECKS:[/bold cyan]",
        "  String literals passed positionally to a Rich console print:",
        "  [dim]console.print(...)[/dim], [dim]self.console.print(...)[/dim], [dim]rich.print(...)[/dim],",
        "  and a bare [dim]print(...)[/dim] ONLY where the module did",
        "  [dim]from rich import print[/dim] -- stdlib print renders no markup, so",
        "  flagging it would be a false positive.",
        "",
        "  Call sites are found with the [dim]ast[/dim] module, never a raw-text regex:",
        "  only AST can tell a call ARGUMENT from an unrelated string, and only",
        "  AST can exclude an f-string's [dim]{d\\['k']}[/dim] subscript structurally.",
        "",
        "[bold cyan]THE ORACLE -- RICH'S OWN MACHINERY:[/bold cyan]",
        "  The checker never hand-rolls a bracket regex. It cannot drift from",
        "  Rich's real behaviour because it asks Rich:",
        "",
        "  1. [green]rich.markup.RE_TAGS[/green] finds the tags -- the exact regex Rich",
        "     itself uses. This is why the safe families below are safe",
        "     mechanically, not by special case.",
        "  2. [green]rich.style.Style.parse()[/green] judges each tag, on the style string",
        "     Rich would build from it ([dim]rich.markup.Tag[/dim] partitions on [dim]=[/dim]).",
        "     Parses -> a real style, the author meant it.",
        "     Raises StyleSyntaxError -> literal text, silently eaten.",
        "",
        "[bold cyan]VIOLATIONS:[/bold cyan]",
        "  [red]Bad -- eaten at render time:[/red]",
        '  [dim]console.print("usage: cmd \\[args...]")[/dim]',
        '  [dim]console.print("\\[branch] {msg}")[/dim]',
        '  [dim]console.print("mail from \\[@daemon]")[/dim]',
        '  [dim]console.print("run \\[branches]")[/dim]',
        "",
        "  [green]Good -- escaped, renders literally:[/green]",
        '  [dim]console.print("usage: cmd \\\\\\[args...]")[/dim]',
        '  [dim]console.print("\\\\\\[branch] {msg}")[/dim]',
        "",
        "  Violation message example:",
        "  [dim]2 literal placeholder(s) silently eaten by Rich: \\[args...] on line 42,[/dim]",
        "  [dim]\\[branch] on line 96 - escape as \\\\\\[[/dim]",
        "",
        "  The message NAMES every eaten token and its line -- a bare count",
        "  cannot be acted on. Long lists are capped and say [dim]and N more[/dim].",
        "",
        "[bold cyan]NOT VIOLATIONS -- THE SAFE FAMILIES:[/bold cyan]",
        "  Rich's tag regex requires [dim]\\[[/dim] followed by a-z, #, / or @ and no",
        "  inner [dim]\\[[/dim]. These reach the terminal untouched, verified by render:",
        "",
        "  [green]survives[/green]  [dim]a \\[1,2,3] b[/dim]        -- digits, not a tag",
        "  [green]survives[/green]  [dim]lines \\[42, 78][/dim]     -- digits, not a tag",
        "  [green]survives[/green]  [dim]L\\[42]: msg[/dim]         -- digits, not a tag",
        "  [green]survives[/green]  [dim]a \\[] b[/dim]             -- empty, not a tag",
        "  [green]survives[/green]  [dim]a \\[ spaced ] b[/dim]     -- leading space, not a tag",
        "  [green]survives[/green]  [dim]a \\\\\\[literal] b[/dim]      -- escaped, already correct",
        "",
        "  [green]intentional[/green]  [dim]\\[dim]x\\[/dim][/dim] and [dim]\\[bold cyan]x\\[/][/dim] -- real styles",
        "  [green]intentional[/green]  [dim]\\[link=http://x]y\\[/link][/dim]  -- real link markup",
        "  [green]structural[/green]   [dim]f\"count {d\\['k']} rows\"[/dim]     -- subscript is not a literal",
        '  [green]template[/green]     [dim]"\\[{color}]x".format(...)[/dim]    -- tag filled before Rich',
        "",
        "  [yellow]Loud, not silent:[/yellow] [dim]a \\[/usr/bin] b[/dim] raises rich.errors.MarkupError.",
        "  Closing tags are excluded -- a crash is already caught by tests.",
        "  This standard is only about the losses nothing tells you about.",
        "",
        "[bold cyan]HOW TO FIX:[/bold cyan]",
        "  1. Put a backslash before the opening bracket: [green]\\\\\\[args...][/green]",
        '  2. In an f-string the same escape applies: [green]f"\\\\\\[branch] {name}"[/green]',
        "  3. For runtime values, call [green]rich.markup.escape(value)[/green] before",
        "     interpolating -- a branch name or a filename can contain brackets",
        "  4. Re-run the audit, then LOOK at the rendered output to confirm",
        "",
        "[bold red]ACCEPTANCE CRITERION FOR TESTS -- REQUIRED:[/bold red]",
        "  Assertions MUST be made against RENDERED OUTPUT captured from a real",
        "  Console buffer. Not a MagicMock. Not a real Console whose output is",
        "  never read.",
        "",
        "  [green]Required shape:[/green]",
        "  [dim]buffer = io.StringIO()[/dim]",
        "  [dim]console = Console(file=buffer, force_terminal=False)[/dim]",
        "  [dim]console.print(text)[/dim]",
        '  [dim]assert "\\[args...]" in buffer.getvalue()[/dim]',
        "",
        "  [yellow]Rationale:[/yellow] this defect lives ONLY at render time. A MagicMock",
        "  console records the call arguments -- which are correct, that is the",
        "  whole problem -- and renders nothing, so it agrees by construction.",
        "  A real Console you never read from is the same stand-in wearing a",
        "  better name: a branch can instantiate a real Console, assert on call",
        "  args, and pass green while rendering nothing. Only reading the",
        "  rendered bytes back out of the buffer can catch this class.",
        "",
        "[yellow]SCOPE:[/yellow]",
        "  AUDIT_SCOPE = [bold]all_files[/bold]   -- any .py file can print",
        "  APPLIES_TO  = [bold]production[/bold]  -- test files render nothing a user",
        "  reads, and tests legitimately build broken markup as fixtures.",
        "",
        "[bold cyan]SCORING:[/bold cyan]",
        "  Single check per file: [green]pass[/green] (0 eaten tokens) or [red]fail[/red] (any)",
        "  Score: 100 if passed, 0 if failed",
        "  Threshold: score >= 75 to pass overall",
        "  Line-level bypass filtering is supported -- bypassed lines are",
        "  excluded before counting violations.",
        "",
        "[bold cyan]BYPASS:[/bold cyan]",
        "  Add an entry to [dim].seedgo/bypass.json[/dim]:",
        '  [dim]{"standard": "rich_markup", "file": "path/to/file.py"}[/dim]',
        "  Or bypass specific lines:",
        '  [dim]{"standard": "rich_markup", "file": "file.py", "lines": [42, 78]}[/dim]',
        "",
        "[bold cyan]REFERENCE:[/bold cyan]",
        "  [dim]See: seedgo standards pack (rich_markup)[/dim]",
        "  [dim]Checker: rich_markup_check.py[/dim]",
        "  [dim]Rich source: rich/markup.py (RE_TAGS), rich/style.py (Style.parse)[/dim]",
    ]

    json_handler.log_operation("standard_content_queried", {"standard": "rich_markup"})
    return "\n".join(lines)
