# =================== AIPass ====================
# Name: fresh_clone_content.py
# Description: Fresh Clone Standards Content Handler
# Version: 1.0.0
# Created: 2026-09-08
# Modified: 2026-09-08
# =============================================

"""
Fresh Clone Standards Content Handler

Provides formatted fresh_clone standards content.
Module orchestrates, handler implements.
"""


def get_fresh_clone_standards() -> str:
    """Return formatted fresh_clone standards content with Rich markup.

    Returns:
        str: Formatted standards text with Rich styling
    """
    lines = [
        "[bold cyan]CORE PRINCIPLE:[/bold cyan]",
        "  A test that [bold]builds[/bold] the world it reads has one oracle.",
        "  A test that [bold]asks the host[/bold] for the world has as many",
        "  oracles as there are hosts, and proves none of them.",
        "",
        "[bold cyan]WHY IT EXISTS:[/bold cyan]",
        "  2026-09-08. CI ran on a [bold]fresh clone[/bold] for the first time",
        "  after eight waves of test work had landed overnight on Linux-only",
        "  verification. Two rows went red, and neither was a bug in the code",
        "  it covered — their [bold]expected value came from state a clone does",
        "  not have[/bold]. Both were self_skip cures: a skip stood in front of",
        "  a test that reads THIS machine, the cure removed the skip, and the",
        "  assertion underneath it then depended on the machine. The cure was",
        "  right. What it uncovered had been hidden, not absent.",
        "",
        "  [yellow]Row 1[/yellow] — ai_mail asserted the four live residents",
        "  behind [dim]if projects_tree.is_dir()[/dim] and asserted [dim]{}[/dim]",
        "  in the else arm. [red].gitignore line 178 is projects/* and line 179",
        "  is !projects/README.md[/red], so a clone HAS projects/ and none of",
        "  the four repos. CI took the FIRST arm. The else arm, written to",
        "  protect CI, is unreachable in CI.",
        "",
        "  [yellow]Row 2[/yellow] — daemon pinned",
        "  [dim]sorted(result['structure_checks']) == ['.trinity/local.json',",
        "  '.trinity/observations.json'][/dim] after handing the class constant",
        "  [dim]BRANCH_ROOT = Path(__file__).resolve().parents[1][/dim] to the",
        "  code under test. [red].gitignore line 28 is .trinity/[/red] — a clone",
        "  has no memory files and the producer builds that dict conditionally,",
        "  so on a clone it is empty.",
        "",
        "[bold cyan]WHAT IT CHECKS:[/bold cyan]",
        "  Every test unit is read as an AST and asked one question: would this",
        "  pass on a machine that has only what the repo ships?",
        "",
        "  [yellow]Three species:[/yellow]",
        "  - [red]IGNORED_PATH[/red] — the unit opens, lists, globs or stats a",
        "    path whose spelling matches a root .gitignore pattern and is not",
        "    rooted at tmp_path. The path must be REACHED on the filesystem, not",
        "    merely spelled: a needle in an expected-value list is what a",
        "    producer returned, not a directory this unit opened.",
        "    [bold]This species is about a proof that EVAPORATES, not about a",
        "    test that breaks.[/bold] An assertion that something is ABSENT under",
        "    an ignored path cannot go red on a clone — it stays green forever,",
        "    having quietly stopped checking anything. Loud is recoverable.",
        "    Quiet is not.",
        "  - [red]BOTH_WORLDS[/red] — the unit branches on exists()/is_dir()/",
        "    is_file() of a non-tmp_path path and asserts in BOTH arms. Whichever",
        "    arm this host takes is the only arm anyone runs; the other is prose.",
        "  - [red]DERIVED_EXPECTED[/red] — find_repo_root(), a CLIMB from",
        "    Path(__file__), Path.cwd(), or a module/class constant built from",
        "    one, handed BARE to the code under test as the world it should",
        "    describe, with the answer compared against a value WRITTEN DOWN in",
        "    the file. Class-level constants resolve one hop.",
        "",
        "[bold cyan]THE IGNORE LIST IS A SHIPPED CONSTANT:[/bold cyan]",
        "  Derived by reading the root .gitignore line by line, then frozen into",
        "  the checker. [bold].gitignore is never read at audit time[/bold] — the",
        "  pack is portable and must not depend on the audited project's VCS",
        "  config. [yellow]THE PRICE[/yellow]: another project gets the",
        "  AIPass-shaped list — it under-reports what that project ignores and",
        "  can over-report a segment that project tracks. Read literally, too:",
        "  [dim].seedgo[/dim] and [dim].daemon[/dim] were dropped after",
        "  git ls-files showed both tracked.",
        "",
        "[bold cyan]WHAT IS NEVER FLAGGED:[/bold cyan]",
        "  - [green]a path rooted at tmp_path[/green] — directly or one hop",
        "    through an assignment, a with-as, a for-in, a comprehension or a",
        "    tuple unpack",
        "  - [green]a same-file fixture that hands out a sandbox[/green], to a",
        "    fixed point: hosted_baud -> repo_root -> tmp_path",
        "  - [green]temp_test_dir, by name[/green] — a NAMED exception with a",
        "    reason, never a wildcard: the fleet's own conftest template",
        "    defines it as [dim]tmp_path / test_workspace[/dim], and a conftest",
        "    fixture is invisible to this reader, so the one name the whole",
        "    fleet shares is carried beside the pytest builtins",
        "  - [green]a nested def in a unit that already roots a sandbox[/green]",
        "    — a stand-in the test wrote is the test's own scope, and its",
        "    parameters carry values the unit produced. GATED: a unit naming no",
        "    sandbox at all gets no such acquittal.",
        "  - [green]the test builds the tree it then reads[/green] — a mkdir,",
        "    write_text, write_bytes or touch on the same spelling",
        "  - [green]pytest.skip or skipif behind an existence check[/green] —",
        "    that is a [bold]self_skip[/bold] row, not this rule's business. Two",
        "    findings for one defect and a fleet discounts both.",
        "  - [green]a path reached through a negated region[/green] — the ignore",
        "    file's only ! lines re-admit spawn's template payloads, because a",
        "    template must ship WHOLE",
        "  - [green]a path used only to import or locate the module under",
        "    test[/green] — sys.path.insert, spec_from_file_location and kin",
        "",
        "[bold cyan]IS_DIR() IS NOT A GUARD:[/bold cyan]",
        "  A clone HAS projects/, because !projects/README.md puts it there.",
        '  "Does the directory exist" is a question about packaging; what your',
        "  test depends on is what is [bold]inside[/bold] it. Guard on the",
        "  content, or build the content.",
        "",
        "[bold cyan]HOW TO FIX, IN THIS ORDER:[/bold cyan]",
        "  1. [bold]Give the reader an argument.[/bold] The cure for row 1 is one",
        "     argument wide — the same file already had it twelve lines up:",
        "     tmp_path in, tree built, resolver called WITH the tree.",
        "  2. [bold]Make the fresh-clone claim against an empty tmp_path[/bold],",
        "     as its own collected test. Not in an else arm, not in a skipif, not",
        "     in CI — which you cannot read from here.",
        "  3. If the test really must read this machine, [bold]skip behind an",
        "     existence check[/bold] — and then whether that skip is honest is",
        "     self_skip's question, not this one's.",
        "",
        "[bold cyan]WHAT IT CANNOT SEE — ALL TOWARD FEWER FLAGS:[/bold cyan]",
        "  It does not read .gitignore. It does not follow calls, so a read or a",
        "  build in a helper or a conftest fixture is invisible. A path the code",
        "  under test HANDED BACK is not traced. One hop of name resolution,",
        "  never a chain. And it cannot run the clone — nothing here imports,",
        "  checks out or asks the filesystem anything, because a rule about what",
        "  a stranger's machine has must not be answered by asking this one.",
        "  [bold]It nominates. A human decides.[/bold]",
        "",
        "[yellow]SCOPE:[/yellow]",
        "  AUDIT_SCOPE = [bold]branch_level[/bold]",
        "  Walks [dim]tests/[/dim] then [dim]test/[/dim]; whole tree if neither.",
        "  Test units only — production is not read.",
        "",
        "[bold cyan]SCORING:[/bold cyan]",
        "  Units not flagged / total units, counted per unit: a unit carrying two",
        "  species is one unit to go and read, not two.",
        "  [yellow]ADVISORY[/yellow] — reports a number, never fails a board.",
        "  [bold]Scored from the first run[/bold] — no shadow-only pass, no",
        "  SCORED=False. A rule that cannot repeat its landing must not need to.",
        "  A project with no tests reports [dim]not_applicable[/dim]: zero tests",
        "  measured is not zero quality found.",
        "",
        "[bold cyan]REFERENCE:[/bold cyan]",
        "  [dim]See: pytest_quality standards pack (fresh_clone)[/dim]",
        "  [dim]Checker: fresh_clone_check.py[/dim]",
        "  [dim]Template: templates/fresh_clone_test.py[/dim]",
        "  [dim]Design: DPLAN-0323[/dim]",
    ]

    return "\n".join(lines)
