# =================== AIPass ====================
# Name: platform_oracle_content.py
# Description: Platform Oracle Standards Content Handler
# Version: 1.0.0
# Created: 2026-09-08
# Modified: 2026-09-08
# =============================================

"""
Platform Oracle Standards Content Handler

Provides formatted platform_oracle standards content.
Module orchestrates, handler implements.
"""


def get_platform_oracle_standards() -> str:
    """Return formatted platform_oracle standards content with Rich markup.

    Returns:
        str: Formatted standards text with Rich styling
    """
    lines = [
        "[bold cyan]CORE PRINCIPLE:[/bold cyan]",
        "  Is this test's pass or fail a fact about [bold]the code[/bold], or a",
        "  fact about [bold]the host it ran on[/bold]? The rule is about the",
        "  OUTCOME, not the spelling: not 'does this line contain a slash' but",
        "  'would this assertion have gone the other way on the other runner'.",
        "",
        "[bold cyan]WHY IT EXISTS:[/bold cyan]",
        "  A CI matrix ran Linux and Windows for the first time after eight",
        "  waves of test work landed overnight on Linux-only verification.",
        "  Nobody wrote a bad test — everybody wrote down the only platform",
        "  they could see. The pack had no rule for this: four rules mention",
        "  platform divergence and three mention it only to ACQUIT it;",
        "  [dim]posix_literal[/dim] is the only one that convicts and it is",
        "  scoped to one syntactic shape. This rule is that gap.",
        "",
        "[bold cyan]WHAT IT CHECKS — FIVE SPECIES, AND THE SPLIT IS THE DESIGN:[/bold cyan]",
        "",
        "  [yellow]TWO THAT SCORE:[/yellow]",
        "  - [red]LISTING_ORDER[/red] — an ordered == against a list literal",
        "    whose other side came from iterdir / listdir / glob / rglob /",
        "    scandir / os.walk. [bold]sorted() did not save you:[/bold]",
        "    sorted() over PATH OBJECTS uses PurePath.__lt__, which is",
        "    case-SENSITIVE on POSIX and case-FOLDED under ntpath. POSIX gives",
        "    ['SKILL.md', 'handler.py']; Windows gives ['handler.py',",
        "    'SKILL.md']. Both flavours ship in the stdlib, so the divergence",
        "    is runnable on either host.",
        "  - [red]MODE_INJECTOR[/red] — a failure injected by the FILESYSTEM'S",
        "    MOOD instead of at a seam: chmod to a mode with no write bit,",
        "    stat.S_IREAD-style constants, or a POSIX device path",
        "    ([dim]/dev/null/...[/dim], [dim]/dev/full[/dim],",
        "    [dim]/proc/...[/dim], [dim]/sys/...[/dim]) used to provoke an",
        "    OSError the unit asserts on. Windows ignores POSIX mode bits for",
        "    the owner and has no /dev/null directory semantics, so the write",
        "    SUCCEEDS, nothing raises, and the must-warn assertion reads zero.",
        "",
        "  [yellow]THREE THAT ARE NOMINATED AND NEVER SCORED:[/yellow]",
        "  - [magenta]OSERROR_ATTRIBUTE[/magenta] — asserting on .filename /",
        "    .filename2 / .strerror / .errno / .winerror of a caught exception.",
        "    A Windows subprocess launch fills filename with None ([WinError",
        "    2]); POSIX fills it in.",
        "  - [magenta]UNRESOLVED_TMP_PATH[/magenta] — a temp path compared with",
        "    a plain == against something the code returned, with no resolver",
        "    on either side. The Windows runner's TEMP is an 8.3 short name",
        "    (RUNNER~1) until resolved, and Path == Path compares TEXT.",
        "  - [magenta]SHALLOW_SANDBOX[/magenta] — a sealed cwd whose ANCESTORS",
        "    are not rooted. The patch is not the failure: it lands on the",
        "    pathlib.Path class the module holds, so cwd really is the sandbox.",
        "    Production then walks UP out of it and stops at whichever ancestor",
        "    carries the marker.",
        "",
        "[bold cyan]WHY THREE OF THEM MOVE NO NUMBER:[/bold cyan]",
        "  Each of those three, written as a convicting arm, [bold]flags",
        "  correct tests[/bold]. An assertion on .errno is often right. An",
        "  unresolved comparison is right on most hosts. A sealed cwd is only a",
        "  defect when production walks up, which no reader of a test unit can",
        "  see. An arm that would convict correct tests must not move a number:",
        "  the first time a fleet watches its score drop for a test that was",
        "  right, the score stops being read — and the sound arms stop being",
        "  read with it. They get their own check line, passed True, excluded",
        "  from the score and from the failing count.",
        "",
        "[bold cyan]WHAT IS NEVER FLAGGED:[/bold cyan]",
        "  - [green]sorted(..., key=...)[/green] — any key displaces",
        "    PurePath.__lt__, which is the whole hazard",
        "  - [green]sorted() over STRINGS[/green] — sorted(p.name for p in ...)",
        "    is byte order on every host",
        "  - [green]set / frozenset / Counter[/green] on either side, or sorted",
        "    textually on BOTH sides, or a one-element literal",
        "  - [green]the failure injected at a patched seam[/green] — patch on",
        "    open / write_text / write_bytes / os.replace / Path.open, or an",
        "    OSError side_effect. That IS the cure, so it can never be flagged",
        "  - [green]/dev/null exactly[/green] — as a sink it is correct and",
        "    portable; it is /dev/null used as a DIRECTORY that is the species",
        "  - [green]a resolver on either side[/green], or a unit that rebinds",
        "    the sandbox through one: tmp_path = tmp_path.resolve()",
        "  - [green]two things the TEST built[/green] — the produced side must",
        "    TRACE to a call the subject made (tuple unpack included) or to a",
        "    parameter production hands a spy. Positive evidence, not the",
        "    absence of sandbox evidence",
        "  - [green]an OS error the unit manufactured[/green] — a stand-in that",
        "    raises OSError(errno.EXDEV, ...) puts the TEST'S literal in .errno,",
        "    and a literal is the same number on every platform",
        "  - [green]a furnished sandbox[/green] — a unit that mkdirs or writes",
        "    inside it is not relying on what an ancestor holds",
        "",
        "[bold cyan]HOW TO FIX, ONE CURE PER SPECIES:[/bold cyan]",
        "  1. [bold]Assert the set, or sort the strings[/bold] — not the Paths.",
        "  2. [bold]Inject at the seam[/bold] — side_effect=OSError, never the",
        "     kernel's mood.",
        "  3. [bold]Assert the type and the chain[/bold], and put the name in",
        "     OUR wrapper's message, which we fill on every platform.",
        "  4. [bold]Resolve both sides[/bold], or os.path.samefile.",
        "  5. [bold]Patch a seam the module owns[/bold] by the module's own",
        "     name, and root the sandbox if the walk itself is the claim.",
        "  6. [bold]Run the module's EXISTING pins under every lane you add[/bold],",
        "     not just the new cases -- a forced-darwin cure turned an old",
        "     never-spawns pin red on macOS and 25 units red on Windows.",
        "",
        "[bold cyan]THREE DIVERGENCES A FAKE CANNOT MANUFACTURE:[/bold cyan]",
        "  - a read on a pid AFTER the call that ends it: Linux answers a",
        "    zombie's pgid, macOS answers ESRCH -- read while alive, assert held",
        "  - [dim]os.kill(pid, 0)[/dim] on Windows terminates the target",
        "  - a cwd inside a tree being deleted: Windows refuses (WinError 32)",
        "",
        "[bold cyan]IT NEVER ASKS THE RUNNING MACHINE:[/bold cyan]",
        "  [dim]/dev/full[/dim] is judged as text and Path ordering from the",
        "  shape of the comparison. A portability rule that consulted the host",
        "  would report a different standard on every leg of the matrix, which",
        "  is the exact defect it exists to find — and it is why these findings",
        "  mean the same thing run from either runner.",
        "",
        "[bold cyan]WHAT IT CANNOT SEE — ALL TOWARD FEWER FLAGS:[/bold cyan]",
        "  It does not follow calls, so a chmod in a helper or a listing in a",
        "  fixture is invisible, and so is the seam patch that would acquit it.",
        "  It cannot see where an exception came from — that is the stated",
        "  reason OSERROR_ATTRIBUTE nominates. It reads ONE HOP and stops. A",
        "  flagged site may be correct for a reason a human can see and the",
        "  checker cannot. [bold]It nominates. A human decides.[/bold]",
        "",
        "[yellow]SCOPE:[/yellow]",
        "  AUDIT_SCOPE = [bold]branch_level[/bold]",
        "  Walks [dim]tests/[/dim] then [dim]test/[/dim]; whole tree if neither.",
        "  Production is not read — every species lives in the test unit.",
        "",
        "[bold cyan]SCORING:[/bold cyan]",
        "  Units not flagged by a SCORING species / total units, counted per",
        "  unit: a unit carrying both scoring species is one unit to go and",
        "  read, not two. Nominations are deduped separately and reported in",
        "  their own line — a unit can appear in both, because that line is not",
        "  a penalty.",
        "  [yellow]ADVISORY[/yellow] — reports a number, never fails a board.",
        "  A project with no tests reports [dim]not_applicable[/dim]: zero",
        "  tests measured is not zero quality found.",
        "",
        "[bold cyan]REFERENCE:[/bold cyan]",
        "  [dim]See: pytest_quality standards pack (platform_oracle)[/dim]",
        "  [dim]Checker: platform_oracle_check.py[/dim]",
        "  [dim]Template: templates/platform_oracle_test.py[/dim]",
        "  [dim]Design: DPLAN-0323[/dim]",
    ]

    return "\n".join(lines)
