# =================== AIPass ====================
# Name: posix_literal_content.py
# Description: Posix Literal Standards Content Handler
# Version: 1.1.0
# Created: 2026-09-01
# Modified: 2026-09-08
# =============================================

"""
Posix Literal Standards Content Handler

Provides formatted posix_literal standards content.
Module orchestrates, handler implements.
"""


def get_posix_literal_standards() -> str:
    """Return formatted posix_literal standards content with Rich markup.

    Returns:
        str: Formatted standards text with Rich styling
    """
    lines = [
        "[bold cyan]CORE PRINCIPLE:[/bold cyan]",
        "  A path claim that is only true on the platform it was written",
        "  on is an assertion about one host, written as if it were about",
        "  all of them.",
        '  [dim]Path("/tmp").resolve()[/dim] is [green]/tmp[/green] on POSIX and',
        "  [yellow]D:\\tmp[/yellow] under ntpath, because a rooted literal is",
        "  DRIVE-RELATIVE there — so the assertion underneath accuses code",
        "  that is working perfectly.",
        "  And the reverse: [dim]str(some_path)[/dim] spells the separator",
        "  the HOST's way, so a literal like [dim]apps/x.py[/dim] on the other",
        "  side of the == is right on exactly one leg of a CI matrix.",
        "",
        "[bold cyan]WHAT IT CHECKS:[/bold cyan]",
        "  Every test unit is read as an AST and asked where its path",
        "  literals go, and where the text it compares them with came from.",
        "",
        "  [yellow]Flagged — POSIX-LITERAL (arms 1-2):[/yellow]",
        '  - [red]Path("/tmp").resolve()[/red] — a path CONSTRUCTOR over a',
        "    rooted literal, with resolve() called on it",
        '  - [red]os.path.realpath("/tmp")[/red] / [red]abspath[/red] — a',
        "    resolver function over a rooted literal",
        "",
        "  [yellow]Flagged — RENDERED-PATH (arm 3, SCORED):[/yellow]",
        '  - [red]str(p) == "pkg/gamma.py"[/red] — the TEST wrote the',
        "    rendering down ([dim]str(x)[/dim], an f-string, [dim]%s[/dim]),",
        "    so the test owns the dialect and nothing off-screen can",
        "    make the line right",
        "",
        "  [yellow]Nominated — RETURNED-PATH (arm 3, NOT SCORED):[/yellow]",
        '  - [red]result["relative_path"] == "pkg/gamma.py"[/red] — the value',
        "    came BACK from the code under test (a subscript, an attribute,",
        "    a call result), so whether the producer normalised is off-screen",
        "  - reported in its own check line with [green]passed: True[/green],",
        "    outside the score and outside the failing count",
        "",
        "  [yellow]Flagged — REPR-HAYSTACK (arm 4):[/yellow]",
        "  - [red]assert str(p) in str(mock.call_args)[/red] — call_args",
        "    renders through repr(), which DOUBLES a backslash separator, so",
        "    even a correctly built expected string is not in there",
        "  - cure: assert on [dim]call_args.args[n][/dim] or .kwargs",
        "",
        "  [yellow]Not flagged:[/yellow]",
        '  - [green]registry.resolve("/tmp", ...)[/green] — any other object\'s',
        "    resolve(); a branch-name lookup shares the verb and nothing else",
        '  - [green]Path("logs").resolve()[/green] — a relative fragment',
        "    carries no platform claim",
        "  - [green]tmp_path / os.sep[/green] — a path that was derived,",
        "    not written down",
        '  - [green]p.as_posix() == "a/b.py"[/green] — posix ON PURPOSE, which',
        "    is the cure a flagged site is rewritten into",
        '  - [green]"anthropic/claude-3.5-sonnet"[/green], [green]"11/10"[/green],',
        "    a URL, a pytest nodeid — a slash is not a separator",
        "",
        "[bold cyan]WHY THE RECEIVER AND NOT THE NAME:[/bold cyan]",
        "  Measured over 721 test files before the rule existed: keying on",
        "  the method NAME found 10 sites and [yellow]six of them were a",
        "  branch-name resolver[/yellow] holding a literal it never resolves.",
        "  Keyed on the receiver it nominates none of those. A rule with that",
        "  acquittal rate is one a fleet learns to ignore inside a week.",
        "",
        "[bold cyan]IT NOMINATES, IT DOES NOT CONVICT:[/bold cyan]",
        "  A test that deliberately exercises POSIX spelling — a fence",
        "  refusing [dim]/etc/passwd[/dim] — is a legitimate site and stays.",
        "  What the flag buys is that the decision gets [bold]made[/bold]",
        "  rather than inherited from whichever platform the author was",
        "  standing on.",
        "",
        "[bold cyan]HOW TO FIX:[/bold cyan]",
        "  Derive the path from [dim]tmp_path[/dim] or [dim]os.sep[/dim], or",
        "  state the claim out loud: parametrise both dialects, or assert on",
        "  [dim]Path.parts[/dim] rather than on a spelling. Where the literal",
        "  IS the subject, keep it and say so.",
        "  RENDERED-PATH and RETURNED-PATH get the [bold]same cure[/bold]:",
        "  compare Path to Path, or [dim]as_posix()[/dim] on both sides. A",
        "  nomination has one extra outcome — go and read the producer; if it",
        "  already ends in [dim].as_posix()[/dim], the test was right.",
        "",
        "[yellow]SCOPE:[/yellow]",
        "  AUDIT_SCOPE = [bold]branch_level[/bold]",
        "  Walks [dim]tests/[/dim] then [dim]test/[/dim]; whole tree if neither.",
        "",
        "[bold cyan]WHY ARM 3 IS SPLIT — THE MEASUREMENT:[/bold cyan]",
        "  The undivided arm's first fleet run returned [bold]64 rows, 27 of",
        "  them on seedgo[/bold] — and most of seedgo's are correct portable",
        "  code: [dim]corpus.py:202[/dim] returns",
        "  [dim]path.relative_to(root).as_posix()[/dim], so those strings are",
        "  posix on every host, on purpose. They are the SAME AST shape as the",
        "  rows that broke CI; the difference is off-screen, in the producer.",
        "  A scoring arm that convicts correct code is how a standard gets",
        "  switched off. So the arm scores what the checker CAN see — the",
        "  rendering the test wrote down — and nominates the rest.",
        "  Measured over 18 branches: 353 comparisons hold a slashed literal,",
        "  155 have a rendering or a returned value opposite, the narrowing",
        "  lands on 68, and [bold]2 of the 70 fleet rows score[/bold].",
        "",
        "[bold cyan]WHAT THE NOMINATED HALF KEYS ON — SAID OUT LOUD:[/bold cyan]",
        "  A returned value cannot prove it came from a Path. So the arm",
        "  reads the [bold]accompanying evidence[/bold]: a path-ish spelling",
        "  ([dim]path, dir, file, root, src, dest, target, location[/dim]),",
        "  or a Path built anywhere in the unit. That is circumstantial and",
        "  it is written down rather than dressed up as a proof — a second",
        "  reason it does not move a number.",
        "",
        "[bold cyan]LIMITS — ALL TOWARD FEWER FLAGS:[/bold cyan]",
        "  Reads the RECEIVER, so a literal handed through a variable is not",
        "  seen. Walks TEST UNITS, so a fixture or module-level literal is not",
        "  seen. Nothing here follows a call.",
        "  Arm 3 reads ONE comparison, and cannot see an [dim].as_posix()[/dim]",
        "  that lives in production. Arm 4 follows a rendered call record one",
        "  hop through a local name and no further.",
        "",
        "[bold cyan]SCORING:[/bold cyan]",
        "  Units with no [bold]scoring[/bold] finding / total units, counted",
        "  [bold]per unit[/bold] — four literals in one test is one unit to",
        "  go and read, not four.",
        "  [yellow]RETURNED-PATH is outside the number entirely[/yellow] — its",
        "  own check line, [green]passed: True[/green], reported under",
        "  [dim]nominations[/dim] rather than [dim]violations[/dim].",
        "  [yellow]ADVISORY[/yellow] — reports a number, never fails a board.",
        "  A project with no tests reports [dim]not_applicable[/dim]: zero",
        "  tests measured is not zero quality found.",
        "",
        "[bold cyan]REFERENCE:[/bold cyan]",
        "  [dim]See: pytest_quality standards pack (posix_literal)[/dim]",
        "  [dim]Checker: posix_literal_check.py[/dim]",
        "  [dim]Design: DPLAN-0323 / FPLAN-0469[/dim]",
    ]

    return "\n".join(lines)
